const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
test('a complete release passes measured checks and exports a readable ZIP with a truthful manifest',{timeout:120000},async()=>{
 const {ReleaseStore,atomicJson}=await import('../../automation/studio/release-store.mjs'),{processMedia}=await import('../../automation/studio/media-engine.mjs'),{renderTrailer}=await import('../../automation/studio/trailer-engine.mjs'),{validateRelease,exportRelease}=await import('../../automation/studio/release-package.mjs'),dir=await fs.mkdtemp(path.join(os.tmpdir(),'cts-package-'));
 try{const store=new ReleaseStore(dir);let r=await store.create({title:'Complete release verification'});const draft=path.join(dir,'drafts',r.episodeId),project=path.join(dir,'projects',r.researchId),postId='post-check',post=path.join(dir,'posts',postId);await fs.mkdir(post,{recursive:true});const ep=await store.episode(r);ep.script=['A sourced test passage.'];ep.description='Reviewed show notes.';await atomicJson(path.join(draft,'episode.json'),ep);await fs.writeFile(path.join(project,'notes.md'),'Verified source notes.');
 await processMedia('ffmpeg',['-y','-v','error','-f','lavfi','-i','sine=frequency=400:duration=1201','-af','loudnorm=I=-16:TP=-1.5:LRA=11',path.join(draft,'episode.mp3')]);await processMedia('ffmpeg',['-y','-v','error','-f','lavfi','-i','color=c=black:s=1400x1400','-frames:v','1',path.join(project,'cover.jpg')]);await processMedia('ffmpeg',['-y','-v','error','-i',path.join(project,'cover.jpg'),'-vf','scale=1080:1350',path.join(post,'slide-1.jpg')]);await atomicJson(path.join(post,'post.json'),{title:r.title,caption:'Test caption',slides:[{}]});
 const cover='project:'+r.researchId+':cover.jpg',audio='draft:'+r.episodeId+':episode.mp3',storyboard={format:'landscape',scenes:[{image:cover,audio,in:0,out:1,caption:'A sourced test passage.',fit:'contain'}],music:null,endCard:''};
 r=await store.update(r.id,{expectedRevision:r.revision,postIds:[postId],showNotes:ep.description,claims:[{id:'test-claim',target:'script',text:ep.script[0],source:'https://example.com/source',verified:true}],brand:{...r.brand,cover,approved:[cover]},carousel:{slides:[{text:'Test slide'}],caption:'Test caption'},storyboard,transcript:{segments:[{start:0,end:1,text:ep.script[0]}],stale:false,timelineRevision:0,audioModified:(await fs.stat(path.join(draft,'episode.mp3'))).mtimeMs},releaseReview:{accountConfirmed:true}});
 r=await store.update(r.id,{expectedRevision:r.revision,carousel:{...r.carousel,exportedPostId:postId}});const trailer='trailer-full-check.mp4';const rendered=await renderTrailer(store,r,storyboard,path.join(project,trailer));assert.equal(rendered.width,1920);assert.equal(rendered.height,1080);await atomicJson(path.join(project,trailer+'.json'),{storyboard});
 const report=await validateRelease(store,r.id);assert.equal(report.ready,true,JSON.stringify(report.issues));const result=await exportRelease(store,r.id);assert.equal(result.manifest.status,'ready-for-review');assert.equal(result.manifest.published,false);assert.ok(result.manifest.files.some(f=>f.name==='captions.srt'));const zip=path.join(project,result.name),out=path.join(dir,'unpacked'),quote=s=>"'"+s.replaceAll("'","''")+"'";await processMedia('powershell.exe',['-NoProfile','-NonInteractive','-Command',`Expand-Archive -LiteralPath ${quote(zip)} -DestinationPath ${quote(out)}`]);const manifest=JSON.parse(await fs.readFile(path.join(out,'manifest.json'),'utf8'));assert.equal(manifest.report.ready,true);assert.ok((await fs.stat(path.join(out,'episode.mp3'))).size>0);
 }finally{assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));await fs.rm(dir,{recursive:true,force:true,maxRetries:10,retryDelay:100});}
});
test('Studio microphone permissions allow only audio at the Studio origin',()=>{const {studioPermission}=require('../studio-permissions.cjs'),url='http://127.0.0.1:4177';assert.equal(studioPermission(url+'/workspace','media',{mediaTypes:['audio']},url),true);assert.equal(studioPermission(url,'media',{mediaType:'audio'},url),true);assert.equal(studioPermission(url,'media',{mediaTypes:['audio','video']},url),false);assert.equal(studioPermission('https://instagram.com','media',{mediaTypes:['audio']},url),false);assert.equal(studioPermission(url,'clipboard-read',{},url),false);});
