const test=require('node:test'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {_electron:electron}=require('D:/Dev/GitHub/ig-studio/node_modules/playwright');
test('Electron release project: linked editors, audio timeline, approved art, Instagram export, trailer and review ZIP',{timeout:240000},async()=>{
 const repo=path.resolve(__dirname,'../..'),port=6100+Math.floor(Math.random()*150),base='http://127.0.0.1:'+port,profile=await fs.mkdtemp(path.join(os.tmpdir(),'cts-release-window-')),jobDir=path.join(profile,'jobs'),headers={'X-CTS':'1','Content-Type':'application/json'};
 const server=spawn(process.execPath,[path.join(repo,'automation/studio/server.mjs')],{env:{...process.env,STUDIO_PORT:String(port),STUDIO_JOB_DIR:jobDir},stdio:['ignore','pipe','pipe'],windowsHide:true});let serverLog='';server.stderr.on('data',c=>serverLog+=c);let app,r,postIds=[];
 async function api(url,method='GET',body){const response=await fetch(base+url,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),data=await response.json();assert.ok(response.ok,JSON.stringify(data));return data;}
 try{
  for(let i=0;i<80;i++){try{if((await fetch(base+'/api/drafts')).ok)break;}catch{}await new Promise(resolve=>setTimeout(resolve,100));}
  r=await api('/api/releases','POST',{title:'Release workflow verification'});
  const {processMedia}=await import('../../automation/studio/media-engine.mjs');const project=path.join(repo,'automation/studio/projects',r.researchId);
  await processMedia('ffmpeg',['-hide_banner','-y','-loglevel','error','-f','lavfi','-i','sine=frequency=440:duration=2','-ar','48000',path.join(project,'test-narration.wav')]);
  await processMedia('ffmpeg',['-hide_banner','-y','-loglevel','error','-f','lavfi','-i','color=c=0x171719:s=1400x1400','-frames:v','1',path.join(project,'approved-test-cover.jpg')]);
  await processMedia('ffmpeg',['-hide_banner','-y','-loglevel','error','-i',path.join(project,'test-narration.wav'),path.join(repo,'automation/studio/drafts',r.episodeId,'episode.mp3')]);await fs.writeFile(path.join(repo,'automation/studio/drafts',r.episodeId,'transcript.json'),JSON.stringify({segments:[{start:0,end:1.5,text:'The first source.',speaker:0}],words:[{start:0,end:.3,text:'The',speaker:0},{start:.3,end:.6,text:'first',speaker:0},{start:.6,end:1.5,text:'source.',speaker:0}]}));
  await api('/api/draft/'+r.episodeId,'PUT',{script:['The first sourced passage.','The second sourced passage.']});await api('/api/project/'+r.researchId+'/notes','PUT',{text:'Source notes for the test release.'});
  const env={...process.env,CTS_TEST_PROFILE:profile,CTS_TEST_URL:base+'/workspace'};delete env.ELECTRON_RUN_AS_NODE;
  app=await electron.launch({executablePath:require('electron'),args:[path.join(__dirname,'fixtures/workspace-window.cjs'),'--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream'],env});const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.locator('#release-picker option[value="'+r.id+'"]').waitFor({state:'attached'});await page.locator('#release-picker').selectOption(r.id);await page.waitForFunction(id=>{try{return window.ctsRelease?.get().id===id;}catch{return false;}},r.id);
  assert.equal(await page.locator('#project').inputValue(),r.researchId);assert.equal(await page.locator('#project').isDisabled(),true);
  await page.locator('[data-view="overview"]').click();await page.screenshot({path:path.join(os.tmpdir(),'crimetime-release-overview.png'),timeout:5000}).catch(()=>{});
  await page.locator('[data-view="script"]').click();await page.waitForFunction(()=>document.querySelector('#script-body').value.includes('first sourced'));await page.locator('[data-chapter="1"]').click();await page.locator('#chapter-up').click();assert.ok((await page.locator('#script-body').inputValue()).startsWith('The second'));await page.locator('#script-save').click();await page.waitForFunction(()=>document.querySelector('#script-state').textContent.includes('previous script kept'));
  await page.locator('[data-view="recording"]').click();await page.locator('#record-connect').click();await page.waitForFunction(()=>!document.querySelector('#record-start').disabled);await page.locator('#record-countdown').fill('0');await page.locator('#record-name').fill('Verification take');await page.locator('#record-start').click();await page.waitForFunction(()=>document.querySelector('#record-state').textContent.startsWith('Recording '));await new Promise(resolve=>setTimeout(resolve,2200));await page.locator('#record-stop').click();await page.waitForFunction(()=>document.querySelector('#record-state').textContent==='Take saved');assert.ok((await api('/api/release/'+r.id)).inventory.some(a=>a.name.includes('Verification take')));
  await page.locator('[data-view="transcript"]').click();await page.locator('#transcript-load').click();await page.locator('[data-segment="0"][data-field="text"]').waitFor();await page.locator('#transcript-word-view').click();await page.locator('[data-segment="1"][data-field="text"]').fill('verified');await page.locator('#transcript-save').click();await page.waitForFunction(()=>document.querySelector('#transcript-state').textContent.includes('saved'));assert.match((await api('/api/release/'+r.id)).transcript.segments[0].text,/verified/);
  await page.locator('[data-view="assistant"]').click();await page.waitForFunction(()=>document.querySelector('#conversation-picker').value);let chatRequest;await page.route('**/conversations/*/stream',async route=>{chatRequest=route.request().postDataJSON();const cid=new URL(route.request().url()).pathname.split('/')[5],entry={id:'mock-stream-turn',at:new Date().toISOString(),provider:'test model',question:chatRequest.question,answer:'A proposed script edit for review.',script:['A proposed replacement passage.'],actions:[],incomplete:false};const file=path.join(repo,'automation/studio/releases',r.id,cid+'.json'),saved=JSON.parse(await fs.readFile(file,'utf8'));saved.turns.push(entry);await fs.writeFile(file,JSON.stringify(saved));await route.fulfill({status:200,contentType:'text/event-stream',body:'data: '+JSON.stringify({type:'token',text:JSON.stringify({answer:entry.answer})})+'\n\n'+'data: '+JSON.stringify({...entry,type:'complete'})+'\n\n'});});await page.locator('[data-chat-context="notes"]').uncheck();await page.locator('#production-question').fill('Propose a clearer opening.');await page.locator('#production-send').click();await page.locator('[data-conversation-script]').waitFor();assert.equal(chatRequest.context.notes,false);await page.locator('[data-conversation-script]').click();await page.locator('#conversation-after').waitFor();assert.match(await page.locator('#conversation-after').textContent(),/proposed replacement/);await page.locator('#conversation-keep').click();assert.ok(!(await api('/api/draft/'+r.episodeId)).script.join(' ').includes('proposed replacement'));
  await page.locator('[data-view="brand"]').click();await page.locator('[data-brand-cover]').click();await page.waitForFunction(()=>window.ctsRelease.get().brand.cover);
  await page.locator('[data-view="carousel"]').click();await page.locator('#carousel-add').click();await page.locator('#slide-text').fill('A source. A story. A release.');await page.locator('#carousel-caption').fill('A verified test caption.');await page.locator('#carousel-save').click();await page.waitForFunction(()=>document.querySelector('#carousel-state').textContent.includes('saved'));
  await page.screenshot({path:path.join(os.tmpdir(),'crimetime-carousel-composer.png'),timeout:5000}).catch(()=>{});await page.locator('#carousel-export').click();await page.waitForFunction(()=>document.querySelector('#carousel-state').textContent.includes('Exported'),null,{timeout:20000});r=await api('/api/release/'+r.id);postIds=r.postIds;assert.equal(postIds.length,1);
  await page.locator('[data-view="mix"]').click();const audio=r.inventory.find(a=>a.name==='test-narration.wav');await page.locator('#mix-source').selectOption(audio.key);await page.locator('#mix-add').click();await page.locator('[data-mix-clip]').waitFor();await page.locator('#mix-playhead').fill('1');await page.locator('#mix-split').click();assert.equal(await page.locator('[data-mix-clip]').count(),2);await page.locator('#mix-undo').click();assert.equal(await page.locator('[data-mix-clip]').count(),1);await page.locator('#mix-save').click();await page.waitForFunction(()=>document.querySelector('#mix-state').textContent.includes('saved'));await page.screenshot({path:path.join(os.tmpdir(),'crimetime-multitrack-editor.png'),timeout:5000}).catch(()=>{});
  await page.locator('#mix-render').click();await page.locator('#mix-use-episode').waitFor({timeout:25000});assert.match(await page.locator('#mix-measurement').textContent(),/LUFS/);
  await page.locator('[data-view="storyboard"]').click();await page.locator('#story-add').click();await page.locator('#scene-image').selectOption(r.brand.cover);await page.locator('#scene-audio').selectOption(audio.key);await page.locator('#scene-out').fill('1');await page.locator('#scene-caption').fill('The source stays with the story.');await page.locator('#scene-apply').click();await page.locator('#story-save').click();await page.waitForFunction(()=>document.querySelector('#story-state').textContent==='Storyboard saved');await page.locator('#story-render').click();await page.locator('#story-results a').waitFor({timeout:70000});
  await page.locator('[data-view="release"]').click();await page.locator('#release-show-notes').fill('A release workflow verification with temporary sources and media.');await page.locator('#release-notes-save').click();await page.locator('#release-incomplete').check();await page.locator('#release-export').click();await page.locator('#release-export-result a').waitFor({timeout:20000});const href=await page.locator('#release-export-result a').getAttribute('href'),zip=Buffer.from(await(await fetch(base+href)).arrayBuffer());assert.equal(zip.readUInt32LE(0),0x04034b50);assert.ok(zip.includes(Buffer.from('incomplete-review')));assert.ok(zip.includes(Buffer.from('manifest.json')));
  await page.setViewportSize({width:1100,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 }catch(e){console.error(e.message);try{for(const job of await api('/api/jobs'))console.error(JSON.stringify(await api('/api/job/'+job.id)));}catch{}if(app){const pages=app.context().pages();await pages[0]?.screenshot({path:path.join(os.tmpdir(),'crimetime-release-failure.png')}).catch(()=>{});}e.message+='\nServer: '+serverLog;throw e;}finally{
  if(app)await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.destroy())).catch(()=>{});await app?.close().catch(()=>{});server.kill();await new Promise(resolve=>setTimeout(resolve,150));
  if(r){const current=await fs.readFile(path.join(repo,'automation/studio/releases',r.id,'release.json'),'utf8').then(JSON.parse).catch(()=>r);for(const [folder,id] of [['releases',r.id],['drafts',r.episodeId],['projects',r.researchId],...(current.postIds||postIds).map(id=>['posts',id])]){const root=path.resolve(repo,'automation/studio',folder),target=path.resolve(root,id);assert.ok(target.startsWith(root+path.sep));await fs.rm(target,{recursive:true,force:true,maxRetries:20,retryDelay:100});}}
  assert.ok(path.resolve(profile).startsWith(path.resolve(os.tmpdir())+path.sep));await fs.rm(profile,{recursive:true,force:true,maxRetries:20,retryDelay:100});
 }
});
