const test = require('node:test');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const { mkdtempSync, rmSync, writeFileSync } = require('node:fs');
const { tmpdir } = require('node:os');
const path = require('node:path');
const { _electron: electron } = require('D:/Dev/GitHub/ig-studio/node_modules/playwright');

test('production desk saves documents and edited audio through real APIs, and dispatches media and chat requests', { timeout: 120000 }, async () => {
  const repo = path.resolve(__dirname, '../..');
  const port = 5100 + Math.floor(Math.random() * 500), base = `http://127.0.0.1:${port}`;
  const profile = mkdtempSync(path.join(tmpdir(), 'cts-workspace-test-'));
  const server = spawn(process.execPath, [path.join(repo, 'automation/studio/server.mjs')], { env: {...process.env, STUDIO_PORT: String(port)}, stdio:'ignore', windowsHide:true });
  let app, id;
  const headers = {'X-CTS':'1','Content-Type':'application/json'};
  try {
    for(let i=0;i<50;i++){try{if((await fetch(base+'/api/drafts')).ok)break;}catch{} await new Promise(r=>setTimeout(r,200));}
    const missingHeader = await fetch(base+'/api/workspace/generate', {method:'POST',body:'{}'});
    assert.equal(missingHeader.status,403);
    const invalid = await fetch(base+'/api/workspace/generate', {method:'POST',headers,body:JSON.stringify({target:'project',id:'../escape',prompt:'test',aspect:'1:1'})});
    assert.equal(invalid.status,400);
    const bypass = await fetch(base+'/api/run',{method:'POST',headers,body:JSON.stringify({action:'workspace-image',output:'C:/invalid.png'})});
    assert.equal(bypass.status,400);
    const env={...process.env,CTS_TEST_PROFILE:profile,CTS_TEST_URL:base+'/workspace'};delete env.ELECTRON_RUN_AS_NODE;
    app=await electron.launch({executablePath:require('electron'),args:[path.join(__dirname,'fixtures/workspace-window.cjs')],env});
    const page=await app.firstWindow(), errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.locator('#new-project').click();
    await page.locator('#new-name').fill(`Workspace check ${Date.now()}`);
    await page.locator('#name-dialog button[value="save"]').click();
    await page.waitForFunction(()=>document.querySelector('#project').value.length>0);
    id=await page.locator('#project').inputValue();
    await page.locator('[data-view="documents"]').click();
    await page.locator('#notes').fill('Verified test note: the recording lasts ten seconds.');
    await page.locator('#save-notes').click();
    await page.waitForFunction(()=>document.querySelector('#save-state').textContent==='Saved just now');
    let project=await (await fetch(base+`/api/project/${id}`)).json();
    assert.match(project.notes,/Verified test note/);
    await page.locator('#file-upload').setInputFiles({name:'source.txt',mimeType:'text/plain',buffer:Buffer.from('Test source document.')});
    await page.waitForFunction(()=>document.querySelector('#files').textContent.includes('source-'));
    await page.locator('#save-document').click();
    await page.locator('#new-name').fill('Production notes');
    await page.locator('#name-dialog button[value="save"]').click();
    await page.waitForFunction(()=>document.querySelector('#files').textContent.includes('Production notes-'));
    await page.screenshot({path:path.join(tmpdir(),'crimetime-desk-documents.png'),fullPage:true});
    const { wavBytes }=await import('../../automation/studio/audio-edit.mjs');
    const samples=Float32Array.from({length:480000},(_,i)=>Math.sin(i/48000*Math.PI*440*2)*.3);
    await page.locator('[data-view="audio"]').click();
    await page.locator('#audio-upload').setInputFiles({name:'voice-test.wav',mimeType:'audio/wav',buffer:Buffer.from(wavBytes([samples],48000))});
    await page.waitForFunction(()=>!document.querySelector('#save-audio').disabled);
    await page.locator('#trim-start').fill('2');await page.locator('#trim-end').fill('6');await page.locator('#fade-in').fill('0.2');await page.locator('#fade-out').fill('0.3');
    await page.locator('#save-audio').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Original audio preserved'));
    project=await (await fetch(base+`/api/project/${id}`)).json();
    const audio=project.files.find(f=>f.name.startsWith('voice-test-edit'));
    assert.ok(audio);
    const wav=await (await fetch(base+`/api/project/${id}/file?name=${encodeURIComponent(audio.name)}`)).arrayBuffer();
    const exportedRate = new DataView(wav).getUint32(24,true);
    assert.equal(wav.byteLength,44+4*exportedRate*2);
    await page.screenshot({path:path.join(tmpdir(),'crimetime-desk-audio.png'),fullPage:true});
    let generation;
    await page.route('**/api/workspace/generate',route=>{generation=route.request().postDataJSON();return route.fulfill({status:202,contentType:'application/json',body:'{"id":"test-generation","done":false}'});});
    await page.locator('[data-view="create"]').click();
    await page.locator('#destination').selectOption('project');
    await page.locator('#prompt').fill('A rain-soaked street in the 1970s, no text.');
    await page.locator('#generate').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Image generation started'));
    assert.equal(generation.id,id);assert.equal(generation.aspect,'4:5');assert.equal(generation.target,'project');
    await page.screenshot({path:path.join(tmpdir(),'crimetime-desk-create.png'),fullPage:true});
    let chatQuestion;
    await page.route('**/api/project/*/chat',route=>{chatQuestion=route.request().postDataJSON().question;return route.fulfill({status:500,contentType:'application/json',body:'{"error":"Test provider is offline"}'});});
    await page.locator('[data-view="chat"]').click();
    await page.locator('[data-question]').first().click();
    await page.locator('#send').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Test provider is offline'));
    assert.match(chatQuestion,/timeline/);assert.match(await page.locator('#question').inputValue(),/timeline/);
    await page.unroute('**/api/project/*/chat');
    await page.route('**/api/project/*/chat',route=>{
      const entry={q:route.request().postDataJSON().question,a:'The saved test note describes a ten-second recording.',at:new Date().toISOString(),skipped:[]};
      // Test-provider response persisted in this test-created folder; no paid API call.
      assert.match(id,/^workspace-check-[0-9]+$/);
      writeFileSync(path.join(repo,'automation/studio/projects',id,'chat.json'),JSON.stringify([entry]));
      return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(entry)});
    });
    await page.locator('#send').click();
    await page.locator('[data-answer]').waitFor();
    await page.locator('[data-answer]').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Answer saved'));
    project=await (await fetch(base+`/api/project/${id}`)).json();
    assert.match(project.notes,/saved test note describes/);
    await page.screenshot({path:path.join(tmpdir(),'crimetime-desk-chat.png'),fullPage:true});
    await page.locator('[data-view="create"]').click();
    await page.locator('[data-kind="trailer"]').click();
    await page.locator('#trailer').click();
    await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Choose an episode first'));
    await page.route('**/api/draft/test-episode',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:'test-episode',title:'Test episode',status:'voiced',fileList:[{name:'episode.mp3',size:100}]})}));
    await page.locator('#episode').evaluate(el=>el.add(new Option('Test episode','test-episode')));
    await page.locator('#episode').selectOption('test-episode');
    await page.waitForFunction(()=>document.querySelector('#episode-summary').textContent.includes('Test episode'));
    const videoJobs=[];
    await page.route('**/api/run',route=>{videoJobs.push(route.request().postDataJSON());return route.fulfill({status:202,contentType:'application/json',body:'{"id":"video-test","done":false}'});});
    await page.locator('#trailer').click();
    await page.locator('#audiogram').click();
    assert.deepEqual(videoJobs.map(j=>j.action),['trailer','social']);
    assert.equal(videoJobs[0].id,'test-episode');
    await page.locator('#focus').click();assert.equal(await page.locator('body').getAttribute('class'),'focus');await page.keyboard.press('Escape');
    assert.deepEqual(errors,[]);
    await page.setViewportSize({width:1100,height:740});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  } finally {
    await app?.close();
    if(id && /^[a-z0-9-]+$/.test(id))await fetch(base+`/api/project/${id}`,{method:'DELETE',headers}).catch(()=>{});
    server.kill();
    if(!path.resolve(profile).startsWith(path.resolve(tmpdir())+path.sep))throw new Error('Invalid test profile');
    rmSync(profile,{recursive:true,force:true});
  }
});
