import { drawSlide } from '/social-canvas.mjs';
export function mountCampaign({api,notice,esc,get,save,refresh,show,download,onBeforeSwitch}){
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let slides=[],selected=0,drag=null,slideDirty=false,renderSequence=0,scenes=[],sceneSelected=0,storyDirty=false;
 $('.rail nav').insertAdjacentHTML('beforeend','<button data-view="brand">Brand kit</button><button data-view="carousel">Instagram composer</button><button data-view="storyboard">Trailer storyboard</button>');
 $('main').insertAdjacentHTML('beforeend',`
 <section class="view" id="view-brand" hidden><div class="section-intro"><h2>Your artwork sets the direction.</h2><p>Import your Canva covers, logos, licensed photos and fonts through the media library. Approve the assets you want this release to use.</p></div><div class="row actions"><button id="brand-import">Open media library</button><button id="brand-refresh">Refresh brand assets</button><button id="brand-prepare-cover">Prepare selected podcast cover</button><label>Template name<input id="brand-template-name" placeholder="CrimeTime portrait"></label><button id="brand-template-save">Save current slide as template</button></div><div id="brand-assets" class="brand-assets"></div><h3>Saved templates</h3><div id="brand-templates"></div></section>
 <section class="view" id="view-carousel" hidden><div class="section-intro"><h2>Build the post, one frame at a time.</h2><p>Drag slides to reorder. Preview safe bounds, preserve your artwork and export in the exact order shown.</p></div><div class="row actions"><label>Destination account<input id="carousel-account" value="crimetimesnacks" maxlength="30"></label><button id="carousel-add">Add slide</button><button id="carousel-save" class="primary">Save carousel</button><button id="carousel-export">Export to Instagram drafts</button><span id="carousel-state" class="hint"></span></div><div class="campaign-layout"><div><div id="carousel-strip" class="carousel-strip"></div><div class="working-panel panel-body"><label>Layout<select id="slide-mode"><option value="text">Text / image story</option><option value="cover">Artwork only</option></select></label><label>Approved artwork<select id="slide-image"><option value="">No image</option></select></label><div class="field-pair"><label>Image fit<select id="slide-fit"><option value="contain">Show whole artwork</option><option value="cover">Crop to frame</option></select></label><label>Text size<input id="slide-font-size" type="number" min="24" max="120" value="64"></label></div><div class="field-pair"><label>Crop horizontal<input id="slide-crop-x" type="range" min="0" max="100" value="50"></label><label>Crop vertical<input id="slide-crop-y" type="range" min="0" max="100" value="50"></label></div><label>Font<select id="slide-font"><option value="Bebas Neue">Bebas Neue</option><option value="Segoe UI">Segoe UI</option><option value="Georgia">Georgia</option></select></label><label>Slide text<textarea id="slide-text" rows="6"></textarea></label><div class="row actions"><button id="slide-up">Move earlier</button><button id="slide-down">Move later</button><button id="slide-remove">Remove slide</button></div><label>Instagram caption<textarea id="carousel-caption" rows="7" maxlength="2200"></textarea></label></div></div><aside><canvas id="carousel-preview" width="1080" height="1350" aria-label="Instagram portrait slide preview"></canvas><p id="slide-overflow" role="status"></p><label class="check-label"><input id="slide-guides" type="checkbox" checked> Show safe area guides in preview</label></aside></div></section>
 <section class="view" id="view-storyboard" hidden><div class="section-intro"><h2>Shape the trailer before it renders.</h2><p>Choose exact audio excerpts and approved visuals. Each scene keeps its source and duration visible.</p></div><div class="row actions"><button id="story-add">Add scene</button><button id="story-save" class="primary">Save storyboard</button><select id="story-format" aria-label="Trailer format"><option value="portrait">Portrait 1080 × 1920</option><option value="landscape">Landscape 1920 × 1080</option></select><button id="story-preview">Render first scene preview</button><button id="story-render">Render full trailer</button></div><div class="campaign-layout"><div><div id="story-scenes" class="story-scenes"></div><div class="working-panel panel-body"><label>Approved still or footage<select id="scene-image"></select></label><label>Audio source<select id="scene-audio"></select></label><div class="field-pair"><label>Audio in, seconds<input id="scene-in" type="number" min="0" step="0.001" value="0"></label><label>Audio out, seconds<input id="scene-out" type="number" min="0.1" step="0.001" value="10"></label></div><label>Caption<textarea id="scene-caption" rows="3" maxlength="240"></textarea></label><label>Visual framing<select id="scene-fit"><option value="contain">Show whole frame</option><option value="cover">Crop to fill</option></select></label><div class="row actions"><button id="scene-apply">Apply scene changes</button><button id="scene-earlier">Move earlier</button><button id="scene-later">Move later</button><button id="scene-remove">Remove scene</button></div><label>Music bed<select id="story-music"><option value="">No music</option></select></label><label>Music volume dB<input id="story-music-gain" type="number" min="-60" max="0" value="-24"></label><label>End card text, shown for 3 seconds<textarea id="story-end" rows="2" maxlength="160"></textarea></label></div></div><aside><div id="scene-preview" class="scene-preview"></div><p id="story-state" role="status"></p><video id="story-player" controls></video><div id="story-results"></div></aside></div></section>`);
 for(const view of ['brand','carousel','storyboard'])$('[data-view="'+view+'"]').onclick=()=>show(view);
 function assets(){return get().inventory;}
 function approved(){const r=get();return assets().filter(a=>r.brand.approved.includes(a.key));}
 async function loadFonts(){const r=get();for(const a of assets().filter(a=>/\.(woff2?|ttf|otf)$/i.test(a.name)&&r.brand.fonts.includes(a.key))){const name='Imported '+a.name;try{const bytes=await(await fetch(a.url)).arrayBuffer(),font=new FontFace(name,bytes);await font.load();document.fonts.add(font);if(![...$('#slide-font').options].some(o=>o.value===name))$('#slide-font').add(new Option(name,name));}catch{notice('Font could not be loaded: '+a.name,true);}}}
 function renderBrand(){const r=get();$('#brand-assets').innerHTML=assets().filter(a=>/\.(png|jpe?g|webp|woff2?|ttf|otf|mp4|webm)$/i.test(a.name)).map(a=>`<article class="brand-asset">${/\.(png|jpe?g|webp)$/i.test(a.name)?`<img src="${esc(a.url)}" alt="${esc(a.name)}">`:`<p class="file-type">${esc(a.name.split('.').pop())}</p>`}<b>${esc(a.name)}</b><label class="check-label"><input type="checkbox" data-brand-approve="${esc(a.key)}" ${r.brand.approved.includes(a.key)?'checked':''}> Approved for this release</label>${/\.(png|jpe?g|webp)$/i.test(a.name)?`<button data-brand-cover="${esc(a.key)}">${r.brand.cover===a.key?'Selected episode cover':'Use as episode cover'}</button><button data-brand-logo="${esc(a.key)}">${r.brand.logo===a.key?'Selected logo':'Use as logo'}</button>`:/\.(woff2?|ttf|otf)$/i.test(a.name)?`<button data-brand-font="${esc(a.key)}">Load this font</button>`:''}</article>`).join('')||'<p class="empty">Import your artwork or fonts in the media library first.</p>';$$('[data-brand-approve]').forEach(el=>el.onchange=async()=>{try{const r=get(),approved=new Set(r.brand.approved);if(el.checked)approved.add(el.dataset.brandApprove);else approved.delete(el.dataset.brandApprove);await save({brand:{...r.brand,approved:[...approved]}});}catch(e){notice(e.message,true);}});for(const role of ['cover','logo','font'])$$('[data-brand-'+role+']').forEach(b=>b.onclick=async()=>{try{const r=get(),key=b.getAttribute('data-brand-'+role),brand={...r.brand,approved:[...new Set([...r.brand.approved,key])]};if(role==='font')brand.fonts=[...new Set([...brand.fonts,key])];else brand[role]=key;await save({brand});renderBrand();await loadFonts();}catch(e){notice(e.message,true);}});$('#brand-templates').innerHTML=(r.brand.templates||[]).map((t,i)=>`<button data-brand-template="${i}">${esc(t.name)}</button>`).join('')||'<p class="hint">Save a composed slide as your reusable template.</p>';$$('[data-brand-template]').forEach(b=>b.onclick=()=>{slides.push({...structuredClone(get().brand.templates[Number(b.dataset.brandTemplate)].slide),id:crypto.randomUUID()});selected=slides.length-1;slideDirty=true;show('carousel');selectSlide();});}
 $('#brand-prepare-cover').onclick=async()=>{try{await api('/api/release/'+get().id+'/use-cover','POST',{});notice('Approved artwork is being prepared as a square podcast cover. See the production queue.');}catch(e){notice(e.message,true);}};
 $('#brand-import').onclick=()=>show('library');$('#brand-refresh').onclick=()=>refresh().then(renderBrand).catch(e=>notice(e.message,true));$('#brand-template-save').onclick=async()=>{try{const name=$('#brand-template-name').value.trim();if(!name||!slides[selected])throw new Error('Name a template and compose a slide first.');const r=get();await save({brand:{...r.brand,templates:[...r.brand.templates,{name,slide:structuredClone(slides[selected])}]}});renderBrand();}catch(e){notice(e.message,true);}};
 async function preview(){const seq=++renderSequence;if(!slides[selected])return;try{const result=await drawSlide($('#carousel-preview'),slides[selected],{assets:assets(),logo:get().brand.logo,account:$('#carousel-account').value,guides:$('#slide-guides').checked,index:selected,count:slides.length});if(seq!==renderSequence)return;$('#slide-overflow').textContent=result.overflow?'Text overflows the safe area. Reduce text or size before exporting.':'Text fits inside the safe area.';$('#slide-overflow').className=result.overflow?'bad':'hint';}catch(e){notice(e.message,true);}}
 function slideOptions(){const previous=$('#slide-image').value;$('#slide-image').innerHTML='<option value="">No image</option>'+approved().filter(a=>/\.(png|jpe?g|webp)$/i.test(a.name)).map(a=>`<option value="${esc(a.key)}">${esc(a.name)}</option>`).join('');$('#slide-image').value=previous;}
 function selectSlide(){selected=Math.max(0,Math.min(selected,slides.length-1));slideOptions();const s=slides[selected]||{};$('#carousel-strip').innerHTML=slides.map((s,i)=>`<button draggable="true" data-slide-select="${i}" ${i===selected?'aria-current="true"':''}>${i+1}<small>${esc(s.mode==='cover'?'Artwork':s.text?.slice(0,36)||'Empty slide')}</small></button>`).join('');$$('[data-slide-select]').forEach(b=>{b.onclick=()=>{selected=Number(b.dataset.slideSelect);selectSlide();};b.ondragstart=()=>drag=Number(b.dataset.slideSelect);b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();moveSlide(drag,Number(b.dataset.slideSelect));};});$('#slide-mode').value=s.mode||'text';$('#slide-image').value=s.image||'';$('#slide-fit').value=s.fit||'contain';$('#slide-font-size').value=s.fontSize||64;$('#slide-font').value=s.font||'Bebas Neue';$('#slide-crop-x').value=s.cropX??50;$('#slide-crop-y').value=s.cropY??50;$('#slide-text').value=s.text||'';preview();}
 function editSlide(){if(!slides[selected])return;Object.assign(slides[selected],{mode:$('#slide-mode').value,image:$('#slide-image').value,fit:$('#slide-fit').value,fontSize:Number($('#slide-font-size').value),font:$('#slide-font').value,cropX:Number($('#slide-crop-x').value),cropY:Number($('#slide-crop-y').value),text:$('#slide-text').value});slideDirty=true;$('#carousel-state').textContent='Unsaved carousel';preview();}
 for(const id of ['slide-mode','slide-image','slide-fit','slide-font-size','slide-font','slide-crop-x','slide-crop-y','slide-text'])$('#'+id).oninput=editSlide;$('#slide-guides').onchange=preview;
 $('#carousel-caption').oninput=()=>slideDirty=true;$('#carousel-account').oninput=()=>{slideDirty=true;preview();};$('#carousel-add').onclick=()=>{if(slides.length>=10)return notice('Use up to 10 slides for this Studio export.',true);slides.push({id:crypto.randomUUID(),mode:'text',text:'',image:null,fontSize:64,fit:'contain'});selected=slides.length-1;slideDirty=true;selectSlide();};
 function moveSlide(from,to){if(from===null||from<0||to<0||to>=slides.length)return;slides.splice(to,0,slides.splice(from,1)[0]);selected=to;slideDirty=true;selectSlide();}
 $('#slide-up').onclick=()=>moveSlide(selected,selected-1);$('#slide-down').onclick=()=>moveSlide(selected,selected+1);$('#slide-remove').onclick=()=>{slides.splice(selected,1);slideDirty=true;selectSlide();};
 async function saveCarousel(){const r=get();await save({account:$('#carousel-account').value.replace(/^@/,''),carousel:{...r.carousel,slides,caption:$('#carousel-caption').value}});slideDirty=false;$('#carousel-state').textContent='Carousel saved';}
 $('#carousel-save').onclick=()=>saveCarousel().catch(e=>notice(e.message,true));
 $('#carousel-export').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{if(!slides.length||!$('#carousel-caption').value.trim())throw new Error('Add slides and an Instagram caption first.');await saveCarousel();const r=get(),names=[],stamp=Date.now();await document.fonts.ready;for(let i=0;i<slides.length;i++){const canvas=document.createElement('canvas'),result=await drawSlide(canvas,slides[i],{assets:assets(),account:r.account,index:i,count:slides.length});if(result.overflow)throw new Error('Slide '+(i+1)+' overflows. Fix it before export.');const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.95)),name=`carousel-${stamp}-slide-${i+1}.jpg`;await api(`/api/project/${r.researchId}/upload?name=${name}`,'POST',blob);names.push(name);}const post=await api('/api/release/'+r.id+'/carousel-export','POST',{names,expectedRevision:r.revision});await refresh();$('#carousel-state').textContent=`Exported ${slides.length} slides to Instagram draft ${post.id}. Review before posting.`;}catch(e){notice(e.message,true);}finally{b.disabled=false;}};
 function storyOptions(){const opts=items=>items.map(a=>`<option value="${esc(a.key)}">${esc(a.name)}</option>`).join('');$('#scene-image').innerHTML='<option value="">Choose approved visual</option>'+opts(approved().filter(a=>/\.(png|jpe?g|webp|mp4|webm)$/i.test(a.name)));const audio=assets().filter(a=>/\.(mp3|wav|m4a|webm|ogg)$/i.test(a.name));$('#scene-audio').innerHTML='<option value="">Choose audio excerpt</option>'+opts(audio);$('#story-music').innerHTML='<option value="">No music</option>'+opts(audio);}
 function selectScene(){sceneSelected=Math.max(0,Math.min(sceneSelected,scenes.length-1));const s=scenes[sceneSelected]||{};$('#story-scenes').innerHTML=scenes.map((s,i)=>`<button data-scene-select="${i}" ${i===sceneSelected?'aria-current="true"':''}>${i===0?'Cold open':`Scene ${i+1}`} · ${Math.max(0,s.out-s.in).toFixed(2)}s<small>${esc(assets().find(a=>a.key===s.image)?.name||'Choose a visual')}</small></button>`).join('');$$('[data-scene-select]').forEach(b=>b.onclick=()=>{sceneSelected=Number(b.dataset.sceneSelect);selectScene();});$('#scene-image').value=s.image||'';$('#scene-audio').value=s.audio||'';$('#scene-in').value=s.in||0;$('#scene-out').value=s.out||10;$('#scene-caption').value=s.caption||'';$('#scene-fit').value=s.fit||'contain';const a=assets().find(a=>a.key===s.image);$('#scene-preview').innerHTML=a?/\.(mp4|webm)$/i.test(a.name)?`<video src="${esc(a.url)}" controls></video>`:`<img src="${esc(a.url)}" alt="${esc(a.name)}">`:'<p class="empty">Select approved artwork or footage.</p>';$('#story-state').textContent=`${scenes.length} scenes · ${scenes.reduce((n,s)=>n+s.out-s.in,0).toFixed(2)}s before end card`;}
 $('#story-add').onclick=()=>{scenes.push({id:crypto.randomUUID(),in:0,out:10,caption:'',fit:'contain',image:null,audio:null});sceneSelected=scenes.length-1;storyDirty=true;selectScene();};
 function applyScene(){if(!scenes[sceneSelected])throw new Error('Add a scene first.');const s={...scenes[sceneSelected],image:$('#scene-image').value,audio:$('#scene-audio').value,in:Number($('#scene-in').value),out:Number($('#scene-out').value),caption:$('#scene-caption').value,fit:$('#scene-fit').value};if(!s.image||!s.audio||!Number.isFinite(s.in)||!Number.isFinite(s.out)||s.in<0||s.out<=s.in||s.out-s.in>90)throw new Error('Choose visual and audio sources with a 0 to 90 second excerpt.');scenes[sceneSelected]=s;storyDirty=true;selectScene();}
 $('#scene-apply').onclick=()=>{try{applyScene();}catch(e){notice(e.message,true);}};function moveScene(to){if(to<0||to>=scenes.length)return;scenes.splice(to,0,scenes.splice(sceneSelected,1)[0]);sceneSelected=to;storyDirty=true;selectScene();}$('#scene-earlier').onclick=()=>moveScene(sceneSelected-1);$('#scene-later').onclick=()=>moveScene(sceneSelected+1);$('#scene-remove').onclick=()=>{scenes.splice(sceneSelected,1);storyDirty=true;selectScene();};
 async function saveStory(){const r=get();await save({storyboard:{...r.storyboard,scenes,format:$('#story-format').value,music:$('#story-music').value||null,musicGain:Number($('#story-music-gain').value),endCard:$('#story-end').value}});storyDirty=false;$('#story-state').textContent='Storyboard saved';}
 $('#story-save').onclick=()=>saveStory().catch(e=>notice(e.message,true));
 async function trailer(preview){await saveStory();const r=get(),j=await api('/api/release/'+r.id+'/render','POST',{kind:'trailer',preview,expectedRevision:r.revision});$('#story-state').textContent='Rendering your saved storyboard...';const poll=setInterval(async()=>{try{const job=await api('/api/job/'+j.id);if(!job.done)return;clearInterval(poll);if(job.code!==0)throw new Error(job.result?.message||'Trailer render failed. Check the job log.');await refresh();const a=get().inventory.find(a=>a.name===job.result.name);if(a){$('#story-player').src=a.url;$('#story-results').innerHTML=`<a href="${esc(a.url)}" download>Download ${esc(a.name)}</a>`;}$('#story-state').textContent='Trailer render complete';}catch(e){clearInterval(poll);notice(e.message,true);}},1000);}
 $('#story-preview').onclick=()=>trailer(true).catch(e=>notice(e.message,true));$('#story-render').onclick=()=>trailer(false).catch(e=>notice(e.message,true));
 async function load(view){const r=get();if(view==='brand'){renderBrand();return;}if(view==='carousel'){if(!slideDirty){slides=structuredClone(r.carousel.slides);$('#carousel-caption').value=r.carousel.caption;$('#carousel-account').value=r.account;}await loadFonts();selectSlide();}if(view==='storyboard'){if(!storyDirty)scenes=structuredClone(r.storyboard.scenes);storyOptions();$('#story-format').value=r.storyboard.format;$('#story-music').value=r.storyboard.music||'';$('#story-music-gain').value=r.storyboard.musicGain??-24;$('#story-end').value=r.storyboard.endCard||'';selectScene();}}
 onBeforeSwitch(async()=>{if(slideDirty)await saveCarousel();if(storyDirty)await saveStory();});
 window.addEventListener('cts-view',e=>{if(['brand','carousel','storyboard'].includes(e.detail))load(e.detail).catch(e=>notice(e.message,true));});window.addEventListener('cts-release',()=>{slideDirty=false;storyDirty=false;slides=[];scenes=[];});window.addEventListener('beforeunload',e=>{if(slideDirty||storyDirty){e.preventDefault();e.returnValue='';}});
}
