export function mountCatalog({api,notice,esc}){
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let settings;
 $('#view-settings').insertAdjacentHTML('beforeend','<div class="working-panel panel-body spaced"><h3>Defaults for each production task</h3><p class="hint">Choose each task independently. These selections use only the named provider; there is no automatic paid fallback.</p><form id="task-default-form"><div id="task-default-fields" class="task-default-fields"></div><button class="primary">Save task defaults</button></form></div>');
 async function load(){settings=await api('/api/settings');$('#task-default-fields').innerHTML=['writing','checking','chat','images','narration'].map(task=>{const selected=settings.taskDefaults?.[task],options=settings.providers.filter(p=>task==='images'?p.id==='gemini':task==='narration'?p.id==='elevenlabs':!['elevenlabs','deepgram'].includes(p.id)),provider=selected?.provider||options.find(p=>p.id===settings.defaultProvider)?.id||options[0].id;return`<div class="field-pair"><label>${esc(task[0].toUpperCase()+task.slice(1))} provider<select data-task-provider="${task}">${options.map(p=>`<option value="${p.id}" ${p.id===provider?'selected':''}>${esc(p.label)}</option>`).join('')}</select></label><label>Model ID<input data-task-model="${task}" value="${esc(selected?.model||settings.providers.find(p=>p.id===provider)?.values[task==='images'?'imageModel':'model']||'')}"></label></div>`;}).join('');$$('[data-task-provider]').forEach(el=>el.onchange=()=>{const task=el.dataset.taskProvider,p=settings.providers.find(p=>p.id===el.value);$('[data-task-model="'+task+'"]').value=p.values[task==='images'?'imageModel':'model']||'';});}
 $('#task-default-form').onsubmit=async e=>{e.preventDefault();try{const taskDefaults={};$$('[data-task-provider]').forEach(el=>taskDefaults[el.dataset.taskProvider]={provider:el.value,model:$('[data-task-model="'+el.dataset.taskProvider+'"]').value});await api('/api/settings','PUT',{provider:'local',taskDefaults});notice('Task defaults saved. Each task will use its selected provider.');}catch(e){notice(e.message,true);}};
 window.addEventListener('cts-provider-catalog',e=>catalog(e.detail));
 function catalog(result){if(!result.models?.length)return;let list=$('#available-models');if(!list){$('#provider-fields').insertAdjacentHTML('beforeend','<datalist id="available-models"></datalist><p class="hint">Model suggestions come from your account. You can still enter a manual ID.</p>');list=$('#available-models');}list.innerHTML=result.models.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('');$$('#provider-fields input').filter(el=>/model/i.test(el.id)).forEach(el=>el.setAttribute('list','available-models'));}
 window.addEventListener('cts-view',e=>{if(e.detail==='settings')load().catch(e=>notice(e.message,true));});load().catch(()=>{});
}
