export function mountConversations({api,notice,esc,get,show,onBeforeSwitch}){
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let cid=null,turns=[],controller=null,proposal=null,projectId=null;
 $('#production-messages').insertAdjacentHTML('beforebegin',`<div id="conversation-tools" hidden><div class="row actions"><select id="conversation-picker" aria-label="Saved conversation"></select><button id="conversation-new">New conversation</button><input id="conversation-title" aria-label="Conversation title" maxlength="120"><button id="conversation-rename">Rename</button></div><div class="row actions"><span class="hint">Include context:</span>${['script','research','notes','assets'].map(k=>`<label class="check-label"><input type="checkbox" data-chat-context="${k}" checked>${k}</label>`).join('')}</div></div>`);
 $('#production-send').insertAdjacentHTML('afterend','<button type="button" id="conversation-stop" hidden>Stop</button>');
 document.body.insertAdjacentHTML('beforeend','<dialog id="conversation-review"><h2>Review the proposed edit</h2><div class="compare-grid"><div><h3>Current</h3><pre class="compare-copy" id="conversation-before"></pre></div><div><h3>Proposed</h3><pre class="compare-copy" id="conversation-after"></pre></div></div><div class="row actions"><button id="conversation-apply" class="primary">Load into editor</button><button id="conversation-keep">Keep current</button></div></dialog>');
 function base(){return'/api/release/'+get().id+'/conversations';}
 async function load(id){if(controller)throw new Error('Stop the current answer before switching conversations.');const c=await api(base()+'/'+id);cid=id;turns=c.turns;$('#conversation-picker').value=cid;$('#conversation-title').value=c.title;render();}
 async function list(){const items=await api(base());$('#conversation-picker').innerHTML=items.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('');return items;}
 async function init(){try{const r=get();$('#conversation-tools').hidden=false;if(projectId!==r.id){cid=null;projectId=r.id;}const items=await list();if(!items.length){const c=await api(base(),'POST',{title:'Production conversation'});await list();await load(c.id);}else await load(cid||items[0].id);}catch(e){if(projectId)notice(e.message,true);}}
 $('#conversation-picker').onchange=()=>load($('#conversation-picker').value).catch(e=>notice(e.message,true));$('#conversation-new').onclick=async()=>{try{if(controller)throw new Error('Stop the current answer first.');const c=await api(base(),'POST',{title:'New production conversation'});await list();await load(c.id);}catch(e){notice(e.message,true);}};
 $('#conversation-rename').onclick=async()=>{try{await api(base()+'/'+cid,'PUT',{title:$('#conversation-title').value});await list();$('#conversation-picker').value=cid;notice('Conversation renamed.');}catch(e){notice(e.message,true);}};
 function actionLabel(a){return a.type==='start_job'?'Run '+a.job:a.type==='select_asset'?'Use asset as '+a.role:'Prepare draft: '+a.title;}
 function render(){$('#production-messages').innerHTML=turns.map((t,i)=>`<article class="message user"><div class="who">YOU</div><div class="text">${esc(t.question)}</div></article><article class="message"><div class="who">${esc(t.provider||'Assistant')} ${t.incomplete?'· INCOMPLETE':''}</div><div class="text">${esc(t.incomplete?partialAnswer(t.answer):t.answer)}</div>${t.error?`<p class="hint">${esc(t.error)}</p><button data-conversation-retry="${i}">Retry question</button>`:''}<div class="row actions">${!t.incomplete&&t.script?`<button data-conversation-script="${i}">Review script edit</button>`:''}${!t.incomplete&&t.caption?`<button data-conversation-caption="${i}">Review caption</button>`:''}${!t.incomplete?(t.actions||[]).map((a,ai)=>`<button data-conversation-action="${i},${ai}">${esc(actionLabel(a))}</button>`).join(''):''}</div><p class="hint" data-conversation-result="${i}"></p></article>`).join('');$$('[data-conversation-retry]').forEach(b=>b.onclick=()=>{$('#production-question').value=turns[Number(b.dataset.conversationRetry)].question;$('#production-question').focus();});for(const kind of ['script','caption'])$$('[data-conversation-'+kind+']').forEach(b=>b.onclick=()=>{const t=turns[Number(b.getAttribute('data-conversation-'+kind))],el=$(kind==='script'?'#script-body':'#script-caption');proposal={kind,before:el.value,after:kind==='script'?t.script.join('\n\n---\n\n'):t.caption};$('#conversation-before').textContent=proposal.before;$('#conversation-after').textContent=proposal.after;$('#conversation-review').showModal();});$$('[data-conversation-action]').forEach(b=>b.onclick=async()=>{const [i,ai]=b.dataset.conversationAction.split(',').map(Number),a=turns[i].actions[ai];b.disabled=true;try{const r=get();if(a.type==='start_job'){await window.ctsProduction.save();const j=await api('/api/run','POST',{id:r.episodeId,action:a.job});$('[data-conversation-result="'+i+'"]').textContent=`Queued ${a.job} for ${r.title}. Job ${j.id}.`;}else if(a.type==='select_asset'){const asset=r.inventory.find(f=>f.key===a.asset);if(!asset)throw new Error('The proposed asset is no longer in this release.');if(a.role==='cover'){await window.ctsRelease.save({brand:{...r.brand,cover:asset.key,approved:[...new Set([...r.brand.approved,asset.key])]}});show('brand');}else{show('mix');$('#mix-source').value=asset.key;notice('Audio selected. Choose its track type and Add as new track.');}}else{$('#release-new').click();setTimeout(()=>$('#release-create-title').value=a.title,150);}}catch(e){notice(e.message,true);}finally{b.disabled=false;}});$('#production-messages').scrollTop=$('#production-messages').scrollHeight;}
 function partialAnswer(raw){const at=raw.indexOf('"answer"');if(at<0)return raw.startsWith('{')?'Preparing a structured answer...':raw;const start=raw.indexOf('"',raw.indexOf(':',at)+1);let out='',escape=false;for(let i=start+1;i<raw.length;i++){const c=raw[i];if(escape){out+=c==='n'?'\n':c;escape=false;}else if(c==='\\')escape=true;else if(c==='"')break;else out+=c;}return out;}
 const legacy=$('#production-chat-form').onsubmit;
 $('#production-chat-form').onsubmit=async e=>{let r;try{r=get();}catch{return legacy(e);}e.preventDefault();if(controller)return;const question=$('#production-question').value.trim();if(!question)return notice('Write a message first.',true);try{await window.ctsProduction.save();if(!cid)await init();controller=new AbortController();$('#production-send').disabled=true;$('#conversation-stop').hidden=false;$('#assistant-state').textContent='Generating with selected context...';$('#production-messages').insertAdjacentHTML('beforeend','<article class="message"><div class="who">GENERATING · INCOMPLETE</div><div class="text" id="streaming-answer"></div></article>');let partial='',buffer='';const response=await fetch(base()+'/'+cid+'/stream',{method:'POST',headers:{'X-CTS':'1','Content-Type':'application/json'},body:JSON.stringify({question,provider:$('#assistant-provider').value,context:Object.fromEntries($$('[data-chat-context]').map(el=>[el.dataset.chatContext,el.checked]))}),signal:controller.signal});if(!response.ok)throw new Error((await response.json()).error);const decoder=new TextDecoder();for await(const chunk of response.body){buffer+=decoder.decode(chunk,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,end);buffer=buffer.slice(end+2);const line=block.split('\n').find(l=>l.startsWith('data:'));if(!line)continue;const event=JSON.parse(line.slice(5));if(event.type==='token'){partial+=event.text;if($('#streaming-answer'))$('#streaming-answer').textContent=partialAnswer(partial);}if(event.type==='complete'){turns.push(event);if(!event.incomplete)$('#production-question').value='';render();}}}}catch(e){notice(e.name==='AbortError'?'Generation stopped. Partial output is kept as incomplete.':e.message,e.name!=='AbortError');}finally{controller=null;$('#production-send').disabled=false;$('#conversation-stop').hidden=true;$('#assistant-state').textContent='Review edits and actions before applying them.';if(cid)setTimeout(()=>load(cid).catch(()=>{}),350);}};
 $('#conversation-stop').onclick=()=>controller?.abort();$('#conversation-keep').onclick=()=>$('#conversation-review').close();$('#conversation-apply').onclick=()=>{try{const el=$(proposal.kind==='script'?'#script-body':'#script-caption');if(el.disabled)throw new Error('Published episodes are read only.');if(el.value!==proposal.before)throw new Error('The editor changed. Review the proposal again.');el.value=proposal.after;el.dispatchEvent(new Event('input',{bubbles:true}));$('#conversation-review').close();show('script');notice('Proposal loaded for review. Save script to keep the edit.');}catch(e){notice(e.message,true);}};
 onBeforeSwitch(()=>{if(controller)throw new Error('Stop the current conversation before switching projects.');});
 window.addEventListener('cts-release',e=>{if(!e.detail){$('#conversation-tools').hidden=true;projectId=null;cid=null;return;}init();});window.addEventListener('cts-view',e=>{if(e.detail==='assistant'){try{get();setTimeout(init,100);}catch{}}});window.addEventListener('beforeunload',e=>{if(controller){e.preventDefault();e.returnValue='';}});
}
