import { spawn } from 'node:child_process';
import { validateTimeline, timelineDuration } from './audio-timeline.mjs';
export function processMedia(exe,args,options={}){return new Promise((resolve,reject)=>{const p=spawn(exe,args,{windowsHide:true,...options});let out='',err='';p.stdout?.on('data',c=>out=(out+c).slice(-1000000));p.stderr?.on('data',c=>err=(err+c).slice(-1000000));p.on('error',()=>reject(new Error(exe+' is unavailable. Install it or check the Studio tools setup.')));p.on('close',code=>code===0?resolve({out,err}):reject(new Error(exe+' could not process this media. '+err.slice(-1000))));});}
export async function probe(file){const {out}=await processMedia('ffprobe',['-v','error','-show_format','-show_streams','-of','json',file]);return JSON.parse(out);}
export function cleanupFilters(c={}){const filters=[];if(c.noise)filters.push('afftdn=nf=-25');if(c.silence)filters.push('silenceremove=start_periods=1:start_duration=0.15:start_threshold=-45dB:stop_periods=-1:stop_duration=0.8:stop_threshold=-45dB');if(c.eq)filters.push('highpass=f=75','equalizer=f=250:t=q:w=1:g=-2','equalizer=f=3000:t=q:w=1:g=2');if(c.compress)filters.push('acompressor=threshold=0.125:ratio=3:attack=15:release=200:makeup=1.4');if(c.deess)filters.push('deesser=i=0.3:m=0.5:f=0.5');return filters;}
export async function mixAudio(store,release,timeline,output,{bypass=false,seconds=null}={}){
 validateTimeline(timeline);const rate=timeline.sampleRate||48000,args=['-hide_banner','-y'],filters=[],tracks=[],narrations=[];let input=0;
 const solo=timeline.tracks.some(t=>t.solo);for(const track of timeline.tracks){if(track.mute||solo&&!track.solo)continue;const clips=[];for(const c of track.clips){const {path}=await store.assetPath(release.id,c.asset),meta=await probe(path),duration=Number(meta.format?.duration);if(!meta.streams.some(s=>s.codec_type==='audio'))throw new Error('This clip has no audio track.');if(!Number.isFinite(duration)||c.out>duration+1/rate)throw new Error('A clip extends past its source recording.');args.push('-i',path);const n=input++,label='clip'+n,length=(Math.round(c.out*rate)-Math.round(c.in*rate))/rate;const f=[`aresample=${rate}`,`atrim=start_sample=${Math.round(c.in*rate)}:end_sample=${Math.round(c.out*rate)}`,'asetpts=PTS-STARTPTS',`volume=${c.gain||0}dB`];if(c.fadeIn)f.push(`afade=t=in:st=0:d=${Math.min(c.fadeIn,length)}`);if(c.fadeOut)f.push(`afade=t=out:st=${Math.max(0,length-c.fadeOut)}:d=${Math.min(c.fadeOut,length)}`);f.push(`adelay=${Math.round(c.start*rate)}S:all=1`);filters.push(`[${n}:a]${f.join(',')}[${label}]`);clips.push('['+label+']');}
 if(!clips.length)continue;const label='track'+tracks.length;filters.push(`${clips.join('')}amix=inputs=${clips.length}:normalize=0:dropout_transition=0,volume=${track.gain||0}dB[${label}]`);tracks.push({label,role:track.role});if(track.role==='narration')narrations.push(label);}
 if(!tracks.length)throw new Error('Add at least one audible clip.');
 const music=tracks.filter(t=>t.role==='music');if(timeline.ducking&&narrations.length&&music.length){const voice=narrations[0],copies=music.map((_,i)=>'duckvoice'+i);filters.push(`[${voice}]asplit=${copies.length+1}[${voice}keep]${copies.map(c=>'['+c+']').join('')}`);tracks.find(t=>t.label===voice).label=voice+'keep';music.forEach((t,i)=>{filters.push(`[${t.label}][${copies[i]}]sidechaincompress=threshold=0.03:ratio=8:attack=15:release=350[${t.label}duck]`);t.label+='duck';});}
 const cleaning=bypass?[]:cleanupFilters(timeline.cleanup);filters.push(`${tracks.map(t=>'['+t.label+']').join('')}amix=inputs=${tracks.length}:normalize=0:dropout_transition=0${cleaning.length?','+cleaning.join(','):''}[mix]`);
 args.push('-filter_complex',filters.join(';'),'-map','[mix]','-ar',String(rate),'-ac','2','-t',String(seconds||timelineDuration(timeline)),'-c:a','pcm_s16le',output);await processMedia('ffmpeg',args);return measureAudio(output);
}
export async function measureAudio(file){const {err}=await processMedia('ffmpeg',['-hide_banner','-i',file,'-af','loudnorm=I=-16:TP=-1.5:LRA=11:print_format=json','-f','null','-']);const at=err.lastIndexOf('{');try{const v=JSON.parse(err.slice(at,err.indexOf('}',at)+1));return{integratedLUFS:Number(v.input_i),truePeakDB:Number(v.input_tp),loudnessRange:Number(v.input_lra),clipping:Number(v.input_tp)>=0};}catch{throw new Error('Audio loudness measurement did not finish.');}}
