import { splitClip, validateTimeline, timelineDuration, captionText } from '/audio-timeline.mjs';
export function mountMix(ctx){
 const {api,notice,esc,get,save,refresh,show,download,onBeforeSwitch}=ctx,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let timeline={tracks:[],sampleRate:48000},selected=null,undo=[],redo=[],dirty=false,playhead=0,zoom=20,offset=0,buffers=new Map(),decoder,previewURL=null,baseRevision=null;
 $('.rail nav').insertAdjacentHTML('beforeend','<button data-view="mix">Audio timeline</button><button data-view="transcript">Transcript & captions</button>');
 $('main').insertAdjacentHTML('beforeend',`<section class="view" id="view-mix" hidden><div class="section-intro"><h2>Give every sound its place.</h2><p>Arrange narration, music and effects. Edits are saved as instructions; source recordings stay intact.</p></div><div class="row actions"><select id="mix-source" aria-label="Audio asset"><option value="">Choose source audio</option></select><select id="mix-role" aria-label="Track type"><option value="narration">Narration</option><option value="music">Music</option><option value="archive">Archival audio</option><option value="effects">Sound effects</option></select><button id="mix-add">Add as new track</button><button id="mix-save" class="primary">Save timeline</button><span id="mix-state" class="hint"></span></div><div class="row actions"><button id="mix-undo">Undo</button><button id="mix-redo">Redo</button><button id="mix-split">Split at playhead</button><button id="mix-remove">Remove selected clip</button><label>Zoom <input id="mix-zoom" type="range" min="5" max="200" value="20"></label><label>View from <input id="mix-offset" type="number" min="0" step="1" value="0"></label><label>Playhead seconds <input id="mix-playhead" type="number" min="0" step="0.000021" value="0"></label></div><div id="mix-timeline" class="mix-timeline"></div><div class="mix-inspector"><div class="working-panel panel-body"><h3>Selected clip</h3><p id="mix-selection" class="hint">Select a clip in the timeline.</p><div class="field-pair">${[['start','Timeline start'],['in','Source in'],['out','Source out'],['gain','Gain dB'],['fadeIn','Fade in seconds'],['fadeOut','Fade out seconds']].map(([id,label])=>`<label>${label}<input data-clip-field="${id}" type="number" step="0.000021" value="0"></label>`).join('')}</div><button id="mix-clip-apply">Apply clip edit</button></div><div class="working-panel panel-body"><h3>Cleanup & mastering</h3><div class="cleanup-options">${[['noise','Reduce steady noise'],['silence','Shorten long silence (changes timing)'],['eq','Speech EQ'],['compress','Voice compression'],['deess','De-ess'],['master','Master to -16 LUFS']].map(([id,label])=>`<label class="check-label"><input type="checkbox" data-cleanup="${id}">${label}</label>`).join('')}<label class="check-label"><input type="checkbox" id="mix-duck"> Duck music under narration</label></div><div class="row actions"><button id="mix-ab-original">Preview original mix</button><button id="mix-ab-clean">Preview cleanup</button><button id="mix-render" class="primary">Render full mix</button></div><p class="hint">A/B previews render the first 15 seconds. Silence cleanup invalidates transcript timing.</p><p id="mix-measurement" class="hint"></p><audio id="mix-player" controls></audio><div id="mix-results"></div></div></div></section>
 <section class="view" id="view-transcript" hidden><div class="section-intro"><h2>The words, in time.</h2><p>Correct text and speaker labels, adjust timestamps and export captions. Click a time to hear the source.</p></div><div class="row actions"><button id="transcript-load">Load Deepgram transcript</button><button id="transcript-save" class="primary">Save corrections</button><button id="transcript-srt">Export SRT</button><button id="transcript-vtt">Export WebVTT</button><button id="transcript-align">Confirm alignment reviewed</button></div><p id="transcript-state" role="status"></p><audio id="transcript-player" controls></audio><div id="transcript-lines"></div></section>`);
 $$('[data-view="mix"],[data-view="transcript"]').forEach(b=>b.onclick=()=>show(b.dataset.view));
 function changed(){dirty=true;$('#mix-state').textContent='Unsaved timeline changes';try{localStorage.setItem('cts-mix-recovery:'+get().id,JSON.stringify(timeline));}catch{}}
 function history(){undo.push(structuredClone(timeline));if(undo.length>100)undo.shift();redo=[];changed();}
 function clip(){const [t,c]=selected||[];return timeline.tracks[t]?.clips[c];}
 function choose(t,c){selected=[t,c];const v=clip();$('#mix-selection').textContent=v?get().inventory.find(a=>a.key===v.asset)?.name||v.asset:'Select a clip.';$$('[data-clip-field]').forEach(el=>el.value=v?.[el.dataset.clipField]||0);render();}
 async function decode(key){if(buffers.has(key))return buffers.get(key);const a=get().inventory.find(a=>a.key===key);if(!a)throw new Error('Audio source is missing.');decoder??=new AudioContext();const r=await fetch(a.url);if(!r.ok)throw new Error('Audio file could not be loaded.');const b=await decoder.decodeAudioData(await r.arrayBuffer());buffers.set(key,b);return b;}
 function render(){const duration=timelineDuration(timeline);$('#mix-timeline').innerHTML=timeline.tracks.map((t,ti)=>`<div class="mix-track"><div class="track-controls"><input aria-label="Track name" data-track-name="${ti}" value="${esc(t.name)}"><label class="check-label"><input type="checkbox" data-track-mute="${ti}" ${t.mute?'checked':''}> Mute</label><label class="check-label"><input type="checkbox" data-track-solo="${ti}" ${t.solo?'checked':''}> Solo</label><label>Track dB<input type="number" min="-36" max="36" value="${t.gain||0}" data-track-gain="${ti}"></label></div><div class="track-lane"><canvas data-track-wave="${ti}" width="1200" height="104" tabindex="0" aria-label="${esc(t.name)} waveform; arrow keys move playhead, S splits selected clip"></canvas><div class="track-clips">${t.clips.map((c,ci)=>`<button data-mix-clip="${ti},${ci}" style="left:${(c.start-offset)*zoom}px;width:${Math.max(36,(c.out-c.in)*zoom)}px" ${selected?.[0]===ti&&selected?.[1]===ci?'aria-current="true"':''}>${esc(get().inventory.find(a=>a.key===c.asset)?.name||'Missing source')}<small>${c.start.toFixed(3)} – ${(c.start+c.out-c.in).toFixed(3)}s</small></button>`).join('')}</div></div></div>`).join('')||'<p class="empty">Add narration or another audio asset to begin your mix.</p>';$('#mix-state').textContent=(dirty?'Unsaved changes':'Saved timeline')+` · ${duration.toFixed(2)} seconds`;$$('[data-mix-clip]').forEach(b=>b.onclick=()=>choose(...b.dataset.mixClip.split(',').map(Number)));for(const property of ['name','mute','solo','gain'])$$('[data-track-'+property+']').forEach(el=>el.onchange=()=>{history();const index=Number(el.getAttribute('data-track-'+property));timeline.tracks[index][property]=['mute','solo'].includes(property)?el.checked:property==='gain'?Number(el.value):el.value;render();});$$('[data-track-wave]').forEach(canvas=>{canvas.onclick=e=>{const rect=canvas.getBoundingClientRect();playhead=Math.max(0,offset+(e.clientX-rect.left)/zoom);$('#mix-playhead').value=playhead.toFixed(6);draw();};canvas.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();playhead=Math.max(0,playhead+(e.key==='ArrowRight'?1:-1)*(e.shiftKey?1:0.01));$('#mix-playhead').value=playhead.toFixed(6);draw();}if(e.key.toLowerCase()==='s')$('#mix-split').click();};});draw();}
 function draw(){$$('[data-track-wave]').forEach(canvas=>{const ti=Number(canvas.dataset.trackWave),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,scale=w/(canvas.clientWidth||w);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#b49438';for(const c of timeline.tracks[ti].clips){const b=buffers.get(c.asset);if(!b){decode(c.asset).then(draw).catch(()=>{});continue;}const data=b.getChannelData(0);ctx.beginPath();for(let x=0;x<w;x++){const time=offset+x/scale/zoom;if(time<c.start||time>=c.start+c.out-c.in)continue;const sample=Math.floor((c.in+time-c.start)*b.sampleRate),end=Math.min(data.length,sample+Math.ceil(b.sampleRate/(zoom*scale)));let peak=0;for(let j=Math.max(0,sample);j<end;j+=Math.max(1,Math.floor((end-sample)/32)))peak=Math.max(peak,Math.abs(data[j]));ctx.moveTo(x,h/2-peak*40);ctx.lineTo(x,h/2+peak*40);}ctx.stroke();}ctx.strokeStyle='#fff';const x=(playhead-offset)*zoom*scale;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();});}
 async function load(){const r=get();if(!dirty){timeline=structuredClone(r.timeline);baseRevision=r.revision;selected=null;undo=[];redo=[];const recovery=localStorage.getItem('cts-mix-recovery:'+r.id);if(recovery){timeline=JSON.parse(recovery);dirty=true;notice('Recovered your unsaved timeline. Review it before saving.');}}$('#mix-source').innerHTML='<option value="">Choose source audio</option>'+r.inventory.filter(a=>/\.(mp3|wav|m4a|ogg|webm)$/i.test(a.name)).map(a=>`<option value="${esc(a.key)}">${esc(a.name)}</option>`).join('');$$('[data-cleanup]').forEach(el=>el.checked=Boolean(timeline.cleanup?.[el.dataset.cleanup]));$('#mix-duck').checked=Boolean(timeline.ducking);render();}
 $('#mix-add').onclick=async()=>{try{const key=$('#mix-source').value;if(!key)throw new Error('Choose an audio file.');const b=await decode(key);history();timeline.tracks.push({id:crypto.randomUUID(),name:$('#mix-role').selectedOptions[0].textContent,role:$('#mix-role').value,gain:0,mute:false,solo:false,clips:[{id:crypto.randomUUID(),asset:key,start:0,in:0,out:Math.floor(b.duration*48000)/48000,gain:0,fadeIn:0,fadeOut:0}]});choose(timeline.tracks.length-1,0);}catch(e){notice(e.message,true);}};
 $('#mix-clip-apply').onclick=()=>{try{const c=clip();if(!c)throw new Error('Select a clip first.');const next=structuredClone(timeline);$$('[data-clip-field]').forEach(el=>next.tracks[selected[0]].clips[selected[1]][el.dataset.clipField]=Number(el.value));validateTimeline(next);history();timeline=next;render();}catch(e){notice(e.message,true);}};
 $('#mix-split').onclick=()=>{try{const c=clip();if(!c)throw new Error('Select a clip to split.');const parts=splitClip(c,playhead,timeline.sampleRate);history();timeline.tracks[selected[0]].clips.splice(selected[1],1,...parts);render();}catch(e){notice(e.message,true);}};
 $('#mix-remove').onclick=()=>{if(!clip())return;history();timeline.tracks[selected[0]].clips.splice(selected[1],1);selected=null;render();};
 $('#mix-undo').onclick=()=>{if(!undo.length)return;redo.push(structuredClone(timeline));timeline=undo.pop();selected=null;changed();render();};$('#mix-redo').onclick=()=>{if(!redo.length)return;undo.push(structuredClone(timeline));timeline=redo.pop();selected=null;changed();render();};
 $('#mix-zoom').oninput=()=>{zoom=Number($('#mix-zoom').value);render();};$('#mix-offset').oninput=()=>{offset=Math.max(0,Number($('#mix-offset').value)||0);render();};$('#mix-playhead').oninput=()=>{playhead=Math.max(0,Number($('#mix-playhead').value)||0);draw();};
 $$('[data-cleanup]').forEach(el=>el.onchange=()=>{history();timeline.cleanup={...timeline.cleanup,[el.dataset.cleanup]:el.checked};});$('#mix-duck').onchange=()=>{history();timeline.ducking=$('#mix-duck').checked;};
 async function persist(){validateTimeline(timeline);await save({timeline});dirty=false;localStorage.removeItem('cts-mix-recovery:'+get().id);$('#mix-state').textContent='Timeline saved';await refresh();}
 $('#mix-save').onclick=()=>persist().catch(e=>notice(e.message,true));
 async function renderMix(preview,bypass){await persist();const r=get(),j=await api('/api/release/'+r.id+'/render','POST',{kind:'mix',preview,bypass,expectedRevision:r.revision});$('#mix-measurement').textContent='Rendering saved mix. Follow the production queue.';const poll=setInterval(async()=>{try{const job=await api('/api/job/'+j.id);if(!job.done)return;clearInterval(poll);if(job.code!==0)throw new Error(job.result?.message||'Mix failed. Check its production log.');await refresh();const asset=get().inventory.find(a=>a.name===job.result.name);if(asset){$('#mix-player').src=asset.url;$('#mix-results').innerHTML=`<a href="${esc(asset.url)}" download>Download ${esc(asset.name)}</a><button id="mix-use-episode">Use this mix as episode narration</button>`;$('#mix-use-episode').onclick=async()=>{try{const response=await api('/api/release/'+get().id+'/use-audio','POST',{asset:asset.key});notice('Episode mastering started. See the production queue.');}catch(e){notice(e.message,true);}};}const m=job.result.measured;$('#mix-measurement').textContent=m?`${m.integratedLUFS} LUFS integrated · ${m.truePeakDB} dBTP · ${m.clipping?'Clipping detected':'No true-peak clipping measured'}`:'No measurement available.';}catch(e){clearInterval(poll);notice(e.message,true);}},1000);}
 $('#mix-ab-original').onclick=()=>renderMix(true,true).catch(e=>notice(e.message,true));$('#mix-ab-clean').onclick=()=>renderMix(true,false).catch(e=>notice(e.message,true));$('#mix-render').onclick=()=>renderMix(false,false).catch(e=>notice(e.message,true));
 let transcript=null,transcriptDirty=false,wordView=false,transcriptPage=0;
 $('#transcript-load').insertAdjacentHTML('afterend','<button id="transcript-word-view">Edit individual words</button><button id="transcript-previous">Previous rows</button><button id="transcript-next">Next rows</button><span id="transcript-page" class="hint"></span>');
 $('#transcript-word-view').onclick=()=>{wordView=!wordView;transcriptPage=0;transcriptRender();};$('#transcript-previous').onclick=()=>{transcriptPage=Math.max(0,transcriptPage-1);transcriptRender();};$('#transcript-next').onclick=()=>{const count=(wordView?transcript?.words:transcript?.segments)?.length||0;transcriptPage=Math.min(Math.max(0,Math.ceil(count/100)-1),transcriptPage+1);transcriptRender();};
 function transcriptRender(){const r=get();if(!transcriptDirty)transcript=structuredClone(r.transcript);if(transcript&&transcript.timelineRevision!==r.timeline.revision)transcript.stale=true;const rows=(wordView?transcript?.words:transcript?.segments)||[];$('#transcript-word-view').textContent=wordView?'Edit caption segments':'Edit individual words';$('#transcript-page').textContent=rows.length?`${transcriptPage*100+1}–${Math.min(rows.length,(transcriptPage+1)*100)} of ${rows.length}`:'No rows';$('#transcript-state').textContent=transcript?transcript.stale?'Alignment is stale. Review timing against the edited audio before export.':'Transcript alignment reviewed':'Load a Deepgram transcript after transcription finishes.';const audio=r.inventory.find(a=>a.type==='draft'&&a.name==='episode.mp3');$('#transcript-player').src=audio?.url||'';$('#transcript-lines').innerHTML=rows.slice(transcriptPage*100,(transcriptPage+1)*100).map((s,index)=>{const i=index+transcriptPage*100;return `<div class="transcript-line"><button data-seek="${s.start}">${Number(s.start).toFixed(2)}s</button><label>In<input data-segment="${i}" data-field="start" type="number" step="0.001" value="${s.start}"></label><label>Out<input data-segment="${i}" data-field="end" type="number" step="0.001" value="${s.end}"></label><label>Speaker<input data-segment="${i}" data-field="speaker" value="${esc(s.speaker??'')}"></label><textarea data-segment="${i}" data-field="text" aria-label="Transcript text">${esc(s.text)}</textarea></div>`;}).join('');$$('[data-seek]').forEach(b=>b.onclick=()=>{$('#transcript-player').currentTime=Number(b.dataset.seek);$('#transcript-player').play().catch(()=>{});});$$('[data-segment]').forEach(el=>el.oninput=()=>{const s=(wordView?transcript.words:transcript.segments)[Number(el.dataset.segment)],f=el.dataset.field;s[f]=['start','end'].includes(f)?Number(el.value):el.value;transcript.corrected=true;transcriptDirty=true;if(wordView){for(const segment of transcript.segments){const words=transcript.words.filter(w=>w.start>=segment.start&&w.start<segment.end);if(words.length)segment.text=words.map(w=>w.text).join(' ');}}try{localStorage.setItem('cts-transcript-recovery:'+get().id,JSON.stringify(transcript));}catch{}$('#transcript-state').textContent='Unsaved transcript corrections';});}
 $('#transcript-load').onclick=async()=>{try{const r=get(),a=r.inventory.find(a=>a.type==='draft'&&a.name==='transcript.json');if(!a)throw new Error('Run Deepgram transcription from the voice booth first.');const raw=await (await fetch(a.url)).json();const audio=r.inventory.find(f=>f.type==='draft'&&f.name==='episode.mp3');await save({transcript:{...raw,stale:Boolean(audio&&a.modified<audio.modified),audioModified:audio?.modified,timelineRevision:r.timeline.revision,source:a.key}});transcriptRender();}catch(e){notice(e.message,true);}};
 $('#transcript-save').onclick=async()=>{try{if(!transcript)throw new Error('Load a transcript.');captionText(transcript.segments);transcript.stale ||= transcript.timelineRevision!==get().timeline.revision;await save({transcript});transcriptDirty=false;localStorage.removeItem('cts-transcript-recovery:'+get().id);$('#transcript-state').textContent=transcript.stale?'Saved; alignment still needs review':'Corrections saved';}catch(e){notice(e.message,true);}};
 $('#transcript-align').onclick=async()=>{try{if(!transcript)throw new Error('Load a transcript.');captionText(transcript.segments);transcript.stale=false;transcript.timelineRevision=get().timeline.revision;transcript.audioModified=get().inventory.find(a=>a.type==='draft'&&a.name==='episode.mp3')?.modified;await save({transcript});transcriptDirty=false;localStorage.removeItem('cts-transcript-recovery:'+get().id);$('#transcript-state').textContent='Alignment marked reviewed';}catch(e){notice(e.message,true);}};
 for(const format of ['srt','vtt'])$('#transcript-'+format).onclick=()=>{try{if(!transcript||transcript.stale||transcript.timelineRevision!==get().timeline.revision)throw new Error('Review transcript timing against the current audio before exporting.');download(new Blob([captionText(transcript.segments,format)],{type:'text/plain'}),get().id+'.'+format);}catch(e){notice(e.message,true);}};
 onBeforeSwitch(async()=>{if(dirty)await persist();if(transcriptDirty){captionText(transcript.segments);transcript.stale ||= transcript.timelineRevision!==get().timeline.revision;await save({transcript});transcriptDirty=false;}});
 window.addEventListener('cts-release',()=>{dirty=false;transcriptDirty=false;transcriptPage=0;try{const recovery=JSON.parse(localStorage.getItem('cts-transcript-recovery:'+get().id));if(recovery){transcript=recovery;transcriptDirty=true;notice('Recovered unsaved transcript corrections.');}}catch{}buffers.clear();load().catch(()=>{});transcriptRenderSafe();});function transcriptRenderSafe(){try{transcriptRender();}catch{}}
 window.addEventListener('cts-view',e=>{if(e.detail==='mix')load().catch(e=>notice(e.message,true));if(e.detail==='transcript')transcriptRenderSafe();});
}
