export function mountProduction({api,notice,esc,download,show,refreshJobs,setEpisode}) {
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 let current=null, changed=false, sending=false, turns=[], settings=null, loading=0;
 const labels={voice:'Make cloned voice',art:'Build cover and cards',social:'Build audiogram',trailer:'Build trailer',elevenlabs:'Make ElevenLabs voice',deepgram:'Transcribe with Deepgram'};
 const enc=encodeURIComponent;
 const nav=$('.rail nav');
 nav.insertAdjacentHTML('afterbegin','<button data-view="assistant">Production chat</button><button data-view="script">Script editor</button>');
 nav.insertAdjacentHTML('beforeend','<button data-view="settings">Provider settings</button>');
 document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/production.css">');
 $('main').insertAdjacentHTML('beforeend',`
 <section id="view-settings" class="view" hidden><div class="section-intro"><h2>Your models. Your voices.</h2><p>Connect writing, images, narration and transcription here. Model IDs are editable so you can use the models available to your account.</p></div><div class="settings-layout"><div id="provider-list" class="provider-list" aria-label="Providers"></div><div class="working-panel panel-body"><h3 id="provider-title">Loading providers...</h3><p id="provider-state" class="hint"></p><form id="provider-form"><label for="provider-key">API key</label><input id="provider-key" type="password" autocomplete="new-password" placeholder="Leave blank to keep the saved key"><p class="hint">Keys saved here are protected for your Windows user account. Saved keys are never returned to this page. Environment keys take priority.</p><div id="provider-fields"></div><label class="check-label"><input id="provider-default" type="checkbox"> Use for production chat and episode writing</label><div class="row actions"><button class="primary" id="provider-save">Save provider</button><button type="button" id="provider-test">Test connection</button></div><label class="check-label"><input id="provider-clear" type="checkbox"> Remove the locally saved key on Save</label><p id="provider-result" role="status" class="hint"></p><div id="voice-options"></div></form></div></div></section>
 <section id="view-script" class="view" hidden><div class="section-intro"><h2>Write it. Read it. Make it yours.</h2><p>Edit the script and Instagram caption together. Script saves keep a previous revision and reset fact checks for review.</p></div><div class="row actions"><select data-production-episode aria-label="Episode to edit"><option value="">Choose an episode</option></select><button id="reload-script">Reload episode</button><span id="script-state" class="hint">Choose an episode</span></div><div class="script-layout"><div class="working-panel panel-body"><label for="script-title">Episode title</label><input id="script-title" disabled><div class="section-heading"><h3>Script</h3><span id="script-count" class="eyebrow">0 WORDS</span></div><textarea id="script-body" class="script-body" disabled placeholder="Your episode script. Separate chapters with a line containing ---."></textarea><div class="row actions"><button id="script-save" class="primary" disabled>Save script</button><button id="script-export" disabled>Export Markdown</button><button id="script-read" disabled>Read-through mode</button></div></div><aside class="context"><h3>Instagram caption</h3><textarea id="script-caption" rows="9" disabled></textarea><div class="rule"></div><h3>Previous revisions</h3><select id="script-revisions" aria-label="Script revisions"><option value="">No revisions loaded</option></select><button id="revision-load" class="spaced">Load revision into editor</button><p class="hint">Loading a revision lets you review it before saving.</p><h3>Production checklist</h3><div id="production-readiness" class="hint">Choose an episode.</div><a class="button spaced" href="/">Review facts and publish</a></aside></div></section>
 <section id="view-assistant" class="view" hidden><div class="production-chat-layout"><div><div class="section-intro"><h2>Take an episode from script to screen.</h2><p>Chat with the selected model about your episode. Review proposed edits, then run production steps from the conversation.</p></div><div class="row actions"><select data-production-episode aria-label="Episode for chat"><option value="">Choose an episode</option></select><select id="assistant-provider" aria-label="Chat model provider"></select></div><div id="production-messages" aria-live="polite"><p class="empty">Select an episode or start one in the panel beside this conversation.</p></div><form id="production-chat-form"><label for="production-question">Message the production assistant</label><textarea id="production-question" rows="4" placeholder="Tighten the opening, draft a sourced Instagram caption, or plan the trailer..."></textarea><div class="row actions"><button id="production-send" class="primary">Send message</button><span id="assistant-state" class="hint">Edits and jobs are proposals until you apply them.</span></div></form></div><aside class="context"><details open><summary>Start an episode</summary><form id="new-episode-form"><label for="new-topic">Case or topic</label><input id="new-topic" required maxlength="200" placeholder="Case name and angle"><label class="spaced" for="new-minutes">Target minutes</label><input id="new-minutes" type="number" min="20" max="120" value="20"><button class="primary spaced" id="new-episode-go">Research and draft</button></form></details><div class="rule"></div><h3>Production tools</h3><div class="production-tools">${Object.entries(labels).map(([id,label])=>`<button data-production-action="${id}">${label}</button>`).join('')}</div><p class="hint">Cloud voice, transcription and model requests use your provider credits. Jobs use the saved script.</p><h3>Instagram post</h3><form id="new-post-form"><label for="new-post-title">Post title</label><input id="new-post-title" required maxlength="120"><button class="spaced" id="new-post-go">Create post draft</button></form><a class="button spaced" href="/instagram">Edit posts and review assets</a><div class="rule"></div><h3>Activity</h3><div id="production-activity" aria-live="polite">No activity loaded.</div></aside></div></section>
 <dialog id="read-dialog"><button id="read-close">Close read-through</button><h2 id="read-title"></h2><article id="read-copy"></article></dialog>`);
 for(const b of $$('[data-view="settings"],[data-view="script"],[data-view="assistant"]'))b.onclick=()=>{show(b.dataset.view);};
 const action=(id,fn)=>$(id).addEventListener('click',async e=>{e.preventDefault();const button=e.currentTarget;button.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{button.disabled=false;}});
 function requireEpisode(){if(!current)throw new Error('Choose an episode first.');return current.id;}
 function markChanged(){changed=true;$('#script-state').textContent='Unsaved changes';count();}
 function count(){const words=$('#script-body').value.trim().split(/\s+/).filter(Boolean).length;$('#script-count').textContent=`${words.toLocaleString()} WORDS · ABOUT ${(words/166).toFixed(1)} MIN`;}
 ['#script-title','#script-body','#script-caption'].forEach(s=>$(s).oninput=markChanged);
 async function refreshEpisodes(){const episodes=await api('/api/drafts');$$('[data-production-episode]').forEach(el=>{el.innerHTML='<option value="">Choose an episode</option>'+episodes.map(e=>`<option value="${esc(e.id)}">${esc(e.title)} · ${esc(e.status)}</option>`).join('');el.value=current?.id||'';});}
 async function loadEpisode(id){if(sending)throw new Error('Wait for the answer before switching episodes.');if(changed)await saveScript();const seq=++loading;const ep=id?await api(`/api/draft/${enc(id)}`):null;if(seq!==loading)return;current=ep;await setEpisode(id);fillEditor();$$('[data-production-episode]').forEach(el=>el.value=id);if(ep){turns=await api(`/api/draft/${enc(id)}/conversation`);await revisions();}else turns=[];renderTurns();}
 $$('[data-production-episode]').forEach(el=>el.onchange=()=>loadEpisode(el.value).catch(e=>{el.value=current?.id||'';notice(e.message,true);}));
 function fillEditor(){changed=false;$('#script-title').value=current?.title||'';$('#script-body').value=(current?.script||[]).join('\n\n---\n\n');$('#script-caption').value=current?.instagramCaption||'';for(const id of ['script-title','script-body','script-caption','script-save'])$('#'+id).disabled=!current||current.status==='published';for(const id of ['script-export','script-read'])$('#'+id).disabled=!current;$('#script-state').textContent=current?current.status==='published'?'Published episode · read only':'Saved episode loaded':'Choose an episode';count();window.dispatchEvent(new Event('cts-script-loaded'));const files=current?.fileList||[];$('#production-readiness').innerHTML=current?[['Script',(current.script||[]).length>0],['Audio',files.some(f=>f.name==='episode.mp3')],['Cover',files.some(f=>f.name==='cover.jpg')],['Trailer',files.some(f=>f.name==='trailer.mp4')],['Facts reviewed',(current.factsToVerify||[]).every((_,i)=>current.factsChecked?.[i])]].map(([label,done])=>`<div class="readiness">${label}<b>${done?'Ready':'Needed'}</b></div>`).join(''):'Choose an episode.';}
 async function saveScript(){const id=requireEpisode();if(!changed)return;const script=$('#script-body').value.split(/\n\s*---\s*\n/).map(s=>s.trim()).filter(Boolean);if(!script.length)throw new Error('The script cannot be empty.');const text=$('#script-body').value, title=$('#script-title').value, caption=$('#script-caption').value;const next=await api(`/api/draft/${enc(id)}`,'PUT',{script,title,instagramCaption:caption,expectedEdited:current.edited||current.created||null});current={...current,...next};changed=text!==$('#script-body').value||title!==$('#script-title').value||caption!==$('#script-caption').value;if(!changed){const scroll=$('#script-body').scrollTop;fillEditor();$('#script-body').scrollTop=scroll;}$('#script-state').textContent=changed?'New unsaved changes':'Saved · previous script kept in revisions';await revisions();if(!changed)window.dispatchEvent(new Event('cts-script-saved'));}
 async function revisions(){const list=await api(`/api/draft/${enc(requireEpisode())}/revisions`);$('#script-revisions').innerHTML='<option value="">Choose a previous version</option>'+list.map(name=>`<option value="${esc(name)}">${new Date(Number(name.split('-')[1])).toLocaleString()}</option>`).join('');}
 action('#script-save',async()=>{await saveScript();notice('Script and caption saved.');});
 action('#reload-script',async()=>{const id=requireEpisode();if(changed){download(new Blob([`# ${$('#script-title').value}\n\n${$('#script-body').value}\n\n## Caption\n${$('#script-caption').value}`],{type:'text/markdown'}),`${id}-unsaved-copy.md`);changed=false;notice('Your unsaved work was downloaded before reloading.');}await loadEpisode(id);});
 action('#script-export',()=>{requireEpisode();download(new Blob([`# ${$('#script-title').value}\n\n${$('#script-body').value}\n\n## Instagram caption\n\n${$('#script-caption').value}`],{type:'text/markdown'}),`${current.id}-script.md`);});
 action('#revision-load',async()=>{const name=$('#script-revisions').value;if(!name)throw new Error('Choose a revision.');if(changed)await saveScript();const old=await api(`/api/draft/${enc(requireEpisode())}/revisions?name=${enc(name)}`);$('#script-body').value=(old.script||[]).join('\n\n---\n\n');$('#script-title').value=old.title||'';$('#script-caption').value=old.instagramCaption||'';markChanged();notice('Previous revision loaded for review. Press Save script to apply it.');});
 action('#script-read',()=>{$('#read-title').textContent=$('#script-title').value;$('#read-copy').textContent=$('#script-body').value;$('#read-dialog').showModal();});$('#read-close').onclick=()=>$('#read-dialog').close();
 window.addEventListener('beforeunload',e=>{if(changed||sending){e.preventDefault();e.returnValue='';}});
 window.addEventListener('cts-save-script',()=>saveScript().catch(e=>notice(e.message,true)));
 function renderTurns(){$('#production-messages').innerHTML=turns.length?turns.map((t,i)=>`<article class="message user"><div class="who">YOU</div><div class="text">${esc(t.question)}</div></article><article class="message"><div class="who">${esc(t.provider)} · ${new Date(t.at).toLocaleTimeString()}</div><div class="text">${esc(t.answer)}</div><div class="row">${t.script?`<button data-apply-script="${i}">Review proposed script</button>`:''}${t.caption?`<button data-apply-caption="${i}">Review caption</button>`:''}${(t.actions||[]).filter(a=>labels[a]).map(a=>`<button data-chat-action="${esc(a)}">${labels[a]}</button>`).join('')}</div></article>`).join(''):'<p class="empty">Ask for an edit, a caption, an artwork brief or the next production steps. The assistant reads this episode’s saved script and research.</p>';$$('[data-apply-script]').forEach(b=>b.onclick=async()=>{if(current?.status==='published')return notice('Published episode scripts are read only.',true);if(changed){try{await saveScript();}catch(e){return notice(e.message,true);}}$('#script-body').value=turns[Number(b.dataset.applyScript)].script.join('\n\n---\n\n');markChanged();show('script');notice('Proposed script loaded for review. Save when you are ready.');});$$('[data-apply-caption]').forEach(b=>b.onclick=()=>{if(current?.status==='published')return notice('Published episodes are read only.',true);$('#script-caption').value=turns[Number(b.dataset.applyCaption)].caption;markChanged();show('script');});$$('[data-chat-action]').forEach(b=>b.onclick=()=>runAction(b.dataset.chatAction).catch(e=>notice(e.message,true)));$('#production-messages').scrollTop=$('#production-messages').scrollHeight;}
 $('#production-chat-form').onsubmit=async e=>{e.preventDefault();if(sending)return;try{const id=requireEpisode(),question=$('#production-question').value.trim();if(!question)throw new Error('Write a message first.');if(changed)await saveScript();sending=true;$('#production-send').disabled=true;$('#assistant-state').textContent='Reading your episode and writing an answer...';const t=await api(`/api/draft/${enc(id)}/conversation`,'POST',{question,provider:$('#assistant-provider').value});turns.push(t);$('#production-question').value='';renderTurns();}catch(e){notice(e.message,true);}finally{sending=false;$('#production-send').disabled=false;$('#assistant-state').textContent='Edits and jobs are proposals until you apply them.';}};
 async function runAction(action){if(!labels[action])throw new Error('Unknown production action.');const id=requireEpisode();if(changed)await saveScript();if(current.status==='published')throw new Error('Published media is locked.');await api('/api/run','POST',{action,id,engine:action==='voice'?'clone':undefined});notice(`${labels[action]} started. Follow activity for the result.`);await refreshJobs();await activity();}
 $$('[data-production-action]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await runAction(b.dataset.productionAction);}catch(e){notice(e.message,true);}finally{b.disabled=false;}});
 $('#new-episode-form').onsubmit=async e=>{e.preventDefault();$('#new-episode-go').disabled=true;try{const topic=$('#new-topic').value.trim(),minutes=Number($('#new-minutes').value);if(!topic||minutes<20||minutes>120)throw new Error('Enter a topic and a length from 20 to 120 minutes.');await api('/api/run','POST',{action:'new',topic,minutes});notice('Research and drafting started. The episode will appear in the selector when it is created.');await activity();}catch(e){notice(e.message,true);}finally{$('#new-episode-go').disabled=false;}};
 $('#new-post-form').onsubmit=async e=>{e.preventDefault();$('#new-post-go').disabled=true;try{await api('/api/run','POST',{action:'post-new',title:$('#new-post-title').value.trim()});notice('Post draft creation started. Open Instagram to edit its slides and caption.');await activity();}catch(e){notice(e.message,true);}finally{$('#new-post-go').disabled=false;}};
 async function activity(){const jobs=await api('/api/jobs');$('#production-activity').innerHTML=jobs.slice(-5).reverse().map(j=>`<details class="activity"><summary>${esc(labels[j.action]||j.action)} · ${j.done?j.code===0?'Complete':'Failed':'Working'}</summary><button data-production-log="${esc(j.id)}">Read job output</button><pre></pre></details>`).join('')||'<p class="hint">No jobs in this server session.</p>';$$('[data-production-log]').forEach(b=>b.onclick=async()=>{try{const j=await api(`/api/job/${enc(b.dataset.productionLog)}`);b.nextElementSibling.textContent=j.log||'Waiting for output...';}catch(e){notice(e.message,true);}});}
 let provider='gemini';
 function renderProvider(){const p=settings.providers.find(p=>p.id===provider);$('#provider-title').textContent=p.label;$('#provider-state').textContent=`${p.configured?'Configured':'Not configured'} · ${p.source}`;$('#provider-key').value='';$('#provider-key').disabled=provider==='local';$('#provider-clear').checked=false;$('#provider-clear').disabled=provider==='local';$('#provider-result').textContent='';$('#voice-options').innerHTML='';$('#provider-default').checked=settings.defaultProvider===provider;$('#provider-default').disabled=['elevenlabs','deepgram'].includes(provider);$('#provider-default').closest('label').hidden=$('#provider-default').disabled;$('#provider-fields').innerHTML=Object.entries(p.values).map(([key,value])=>`<label class="spaced" for="setting-${key}">${({model:'Model ID',writerModel:'Episode writing model',imageModel:'Image generation model',voiceId:'ElevenLabs voice ID',baseUrl:'Local server URL'})[key]}</label><input id="setting-${key}" data-setting="${key}" value="${esc(value)}" autocomplete="off">`).join('');$$('[data-provider]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.provider===provider)));}
 async function loadSettings(){settings=await api('/api/settings');$('#provider-list').innerHTML=settings.providers.map(p=>`<button data-provider="${p.id}"><b>${esc(p.label)}</b><small>${p.configured?'Configured':'Add connection'}</small></button>`).join('');$$('[data-provider]').forEach(b=>b.onclick=()=>{provider=b.dataset.provider;renderProvider();});const selected=$('#assistant-provider').value;$('#assistant-provider').innerHTML=settings.providers.filter(p=>!['elevenlabs','deepgram'].includes(p.id)).map(p=>`<option value="${p.id}">${esc(p.label)} · ${esc(p.values.model||'set model')}</option>`).join('');$('#assistant-provider').value=selected||settings.defaultProvider;renderProvider();}
 $('#provider-form').onsubmit=async e=>{e.preventDefault();$('#provider-save').disabled=true;try{const patch={provider,apiKey:$('#provider-key').value,clearKey:$('#provider-clear').checked,makeDefault:$('#provider-default').checked&&!$('#provider-default').disabled};$$('[data-setting]').forEach(el=>patch[el.dataset.setting]=el.value);await api('/api/settings','PUT',patch);$('#provider-key').value='';await loadSettings();$('#provider-result').textContent='Settings saved. Test the connection to check access.';}catch(e){$('#provider-result').textContent=e.message;}finally{$('#provider-save').disabled=false;}};
 action('#provider-test',async()=>{$('#provider-result').textContent='Testing saved connection...';try{const r=await api('/api/settings/test','POST',{provider});$('#provider-result').textContent=r.message;window.dispatchEvent(new CustomEvent('cts-provider-catalog',{detail:r}));if(r.voices?.length){$('#voice-options').innerHTML='<label for="available-voice">Available voices</label><select id="available-voice"><option value="">Choose a voice</option>'+r.voices.map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('')+'</select><p class="hint">Choose a voice, then Save provider.</p>';$('#available-voice').onchange=()=>$('#setting-voiceId').value=$('#available-voice').value;}}catch(e){$('#provider-result').textContent=e.message;}});
 window.addEventListener('cts-view',async e=>{if(['assistant','script'].includes(e.detail)){try{await refreshEpisodes();const selected=localStorage.getItem('cts-desk-episode');if(selected&&selected!==current?.id)await loadEpisode(selected);}catch(e){notice(e.message,true);}}});
 window.ctsProduction={load:loadEpisode,save:()=>current?saveScript():Promise.resolve(),current:()=>current};
 Promise.all([loadSettings(),refreshEpisodes(),activity()]).catch(e=>notice('Production tools: '+e.message,true));
 setInterval(()=>{if(!$('#view-assistant').hidden){activity().catch(()=>{});refreshEpisodes().catch(()=>{});}},7000);
}
