export function mountRecorder({api,notice,esc,get,refresh,onBeforeSwitch}){
 const $=s=>document.querySelector(s);let stream,recorder,chunks=[],started=0,timer,scrollTimer,audioCtx,analyser,meterTimer,recordingProject=null,pending=null,stashDone=Promise.resolve();
 $('main').insertAdjacentHTML('beforeend',`<section class="view" id="view-recording" hidden><div class="section-intro"><h2>Your script. Your voice.</h2><p>Record a named take while you read. The original recording is saved in this release’s research folder.</p></div><div class="record-layout"><div><article class="teleprompter" id="teleprompter" tabindex="0">Choose a release with a saved script.</article><div class="row actions"><button id="prompter-toggle">Start scrolling</button><button id="prompter-top">Back to top</button><button id="prompter-refresh">Load saved script</button></div></div><aside class="record-controls"><label>Microphone<select id="record-device"><option value="">Default microphone</option></select></label><button id="record-connect">Connect microphone</button><meter class="record-meter" id="record-level" min="0" max="1" value="0" aria-label="Microphone input level"></meter><label>Take name<input id="record-name" value="Narration take" maxlength="65"></label><label>Countdown seconds<input id="record-countdown" type="number" min="0" max="10" value="3"></label><label>Text size<input id="prompter-size" type="range" min="20" max="64" value="28"></label><label>Scroll pixels per second<input id="prompter-speed" type="range" min="5" max="100" value="25"></label><p id="record-state" class="record-state" role="status">Microphone disconnected</p><button id="record-start" class="primary" disabled>Record take</button><button id="record-stop" disabled>Stop and save take</button><button id="record-recover" hidden>Retry saving take</button><p class="hint">Cloud services are not used for microphone recording.</p></aside></div><h3>Recorded takes</h3><div id="record-takes"></div></section>`);
 const db=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('cts-recording-recovery',1);r.onupgradeneeded=()=>r.result.createObjectStore('takes');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 async function stash(value,chunk,index){const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('takes','readwrite'),store=tx.objectStore('takes');store.put({project:value.project,name:value.name,type:chunk.type,chunkCount:index+1},'pending');store.put(chunk,'chunk-'+index);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});d.close();}
 async function clearStash(){const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction('takes','readwrite');tx.objectStore('takes').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});d.close();}
 async function recover(){const d=await db(),value=await new Promise((resolve,reject)=>{const r=d.transaction('takes').objectStore('takes').get('pending');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});if(value&&!value.blob){const saved=[];for(let i=0;i<value.chunkCount;i++){const chunk=await new Promise(resolve=>{const req=d.transaction('takes').objectStore('takes').get('chunk-'+i);req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null);});if(chunk)saved.push(chunk);}value.blob=new Blob(saved,{type:value.type});}d.close();if(value){pending=value;$('#record-recover').hidden=false;$('#record-state').textContent='A recording is available to recover.';}}
 async function connect(){if(recorder?.state==='recording')throw new Error('Stop recording before changing microphones.');stream?.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({audio:$('#record-device').value?{deviceId:{exact:$('#record-device').value}}:true});const devices=await navigator.mediaDevices.enumerateDevices(),selected=stream.getAudioTracks()[0].getSettings().deviceId;$('#record-device').innerHTML=devices.filter(d=>d.kind==='audioinput').map(d=>`<option value="${esc(d.deviceId)}">${esc(d.label||'Microphone')}</option>`).join('');$('#record-device').value=selected;audioCtx??=new AudioContext();await audioCtx.resume();analyser=audioCtx.createAnalyser();analyser.fftSize=1024;audioCtx.createMediaStreamSource(stream).connect(analyser);clearInterval(meterTimer);const data=new Float32Array(analyser.fftSize);meterTimer=setInterval(()=>{analyser.getFloatTimeDomainData(data);$('#record-level').value=Math.min(1,Math.sqrt(data.reduce((n,v)=>n+v*v,0)/data.length)*4);},80);stream.getAudioTracks()[0].onended=()=>{if(recorder?.state==='recording')recorder.stop();$('#record-state').textContent='Microphone disconnected. Saving available audio.';$('#record-start').disabled=true;};$('#record-start').disabled=false;$('#record-state').textContent='Microphone ready';}
 $('#record-connect').onclick=()=>connect().catch(e=>notice('Microphone: '+e.message,true));$('#record-device').onchange=()=>connect().catch(e=>notice(e.message,true));
 async function saveTake(){await stashDone;if(!pending)return;await api(`/api/project/${pending.project}/upload?name=${encodeURIComponent(pending.name)}`,'POST',pending.blob);await clearStash();pending=null;$('#record-recover').hidden=true;$('#record-state').textContent='Take saved';await refresh();renderTakes();}
 $('#record-start').onclick=async()=>{try{const r=get();if(pending)throw new Error('Save the recovered take before recording another.');recordingProject=r.researchId;if(!stream?.active)await connect();$('#record-start').disabled=true;$('#record-connect').disabled=true;let countdown=Math.max(0,Math.min(10,Number($('#record-countdown').value)||0));await new Promise(resolve=>{const tick=()=>{if(countdown<=0)return resolve();$('#record-state').textContent='Recording in '+countdown--;setTimeout(tick,1000);};tick();});chunks=[];const name='take-'+Date.now()+'-'+$('#record-name').value.replace(/[^a-zA-Z0-9 -]/g,'').slice(0,60)+'.webm';const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';recorder=new MediaRecorder(stream,{mimeType:mime});recorder.ondataavailable=e=>{if(!e.data.size)return;chunks.push(e.data);pending={project:recordingProject,name,blob:new Blob(chunks,{type:mime})};const value=pending,chunk=e.data,index=chunks.length-1;stashDone=stashDone.catch(()=>{}).then(()=>stash(value,chunk,index));stashDone.catch(()=>notice('Recording recovery storage is unavailable. Stop and save the take soon.',true));};recorder.onstop=async()=>{clearInterval(timer);clearInterval(meterTimer);stream?.getTracks().forEach(t=>t.stop());audioCtx?.suspend().catch(()=>{});$('#record-stop').disabled=true;$('#record-start').disabled=false;$('#record-connect').disabled=false;try{await saveTake();}catch(e){$('#record-state').textContent='Take recorded; save needs retry';$('#record-recover').hidden=false;notice(e.message,true);}};recorder.onerror=()=>{notice('Recording stopped after a device error. Recover the available take.',true);if(recorder.state!=='inactive')recorder.stop();};recorder.start(1500);started=Date.now();$('#record-stop').disabled=false;timer=setInterval(()=>$('#record-state').textContent='Recording '+((Date.now()-started)/1000).toFixed(0)+' s',200);}catch(e){$('#record-start').disabled=false;$('#record-connect').disabled=false;notice(e.message,true);}};
 $('#record-stop').onclick=()=>{if(recorder?.state!=='inactive')recorder?.stop();};$('#record-recover').onclick=()=>saveTake().catch(e=>notice(e.message,true));
 $('#prompter-size').oninput=()=>$('#teleprompter').style.fontSize=$('#prompter-size').value+'px';$('#prompter-top').onclick=()=>$('#teleprompter').scrollTop=0;
 $('#prompter-toggle').onclick=()=>{if(scrollTimer){clearInterval(scrollTimer);scrollTimer=null;$('#prompter-toggle').textContent='Start scrolling';}else{scrollTimer=setInterval(()=>$('#teleprompter').scrollTop+=Number($('#prompter-speed').value)/20,50);$('#prompter-toggle').textContent='Pause scrolling';}};
 async function script(){const r=get(),ep=await api('/api/draft/'+r.episodeId);$('#teleprompter').textContent=ep.script.join('\n\n');renderTakes();}
 function renderTakes(){let r;try{r=get();}catch{return;}$('#record-takes').innerHTML=r.inventory.filter(a=>/^take-/.test(a.name)).map(a=>`<div class="take-row"><b>${esc(a.name)}</b><audio src="${esc(a.url)}" controls preload="metadata"></audio><a href="${esc(a.url)}" download>Download original take</a></div>`).join('')||'<p class="empty">Your named takes will appear here.</p>';}
 $('#prompter-refresh').onclick=()=>script().catch(e=>notice(e.message,true));window.addEventListener('cts-release',()=>script().catch(()=>{}));window.addEventListener('cts-view',e=>{if(e.detail==='recording'){script().catch(()=>{});recover().catch(()=>{});}});
 onBeforeSwitch(()=>{if(recorder?.state==='recording'||$('#record-connect').disabled)throw new Error('Stop and save this take before switching projects.');stream?.getTracks().forEach(t=>t.stop());clearInterval(meterTimer);});
 window.addEventListener('beforeunload',e=>{if(recorder?.state==='recording'){e.preventDefault();e.returnValue='';}});
}
