export function mountReleaseDesk({api,notice,esc,get,save,refresh,show}){
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let report=null;
 $('.rail nav').insertAdjacentHTML('beforeend','<button data-view="release">Release desk</button>');
 $('main').insertAdjacentHTML('beforeend',`<section class="view" id="view-release" hidden><div class="section-intro"><h2>Review the whole release.</h2><p>Check the episode and campaign together, then export a package with its source list and manifest.</p></div><div class="release-desk-layout"><div><div class="working-panel panel-body"><label>Show notes<textarea id="release-show-notes" rows="12" placeholder="Episode summary, source links, credits and disclosure..."></textarea></label><button id="release-notes-save" class="primary">Save show notes</button></div><div class="working-panel panel-body spaced"><h3>Final review</h3><p id="release-account"></p><label class="check-label"><input id="release-account-confirm" type="checkbox"> I reviewed the intended Instagram account</label><button id="release-validate">Validate release files</button><p id="release-validation-state" role="status"></p><div id="release-validation"></div></div></div><aside><h3>Package contents</h3><div id="release-contents"></div><p class="hint">The ZIP includes script, show notes, captions, artwork, carousel, trailer, source notes and a file manifest. It never marks the episode as published.</p><label class="check-label"><input id="release-incomplete" type="checkbox"> Export an incomplete package for review</label><button id="release-export" class="primary">Export release ZIP</button><div id="release-export-result"></div><a href="/" class="button spaced">Open existing episode publishing review</a></aside></div></section>`);
 $('[data-view="release"]').onclick=()=>show('release');
 function load(){const r=get();$('#release-show-notes').value=r.showNotes;$('#release-account').textContent='Intended account: @'+r.account.replace(/^@/,'');$('#release-account-confirm').checked=Boolean(r.releaseReview.accountConfirmed);$('#release-contents').innerHTML=r.inventory.filter(a=>a.type==='draft'&&['episode.mp3','transcript.json'].includes(a.name)||a.key===r.brand.cover||a.type==='post'||/^trailer-full-/.test(a.name)).map(a=>`<p><a href="${esc(a.url)}" target="_blank" rel="noopener">${esc(a.name)}</a></p>`).join('')||'<p class="empty">Finished media will appear here.</p>';}
 $('#release-notes-save').onclick=async()=>{try{await window.ctsProduction.save();await save({showNotes:$('#release-show-notes').value});await api('/api/draft/'+get().episodeId,'PUT',{description:$('#release-show-notes').value});await window.ctsProduction.load(get().episodeId);notice('Show notes saved.');}catch(e){notice(e.message,true);}};
 $('#release-account-confirm').onchange=()=>save({releaseReview:{...get().releaseReview,accountConfirmed:$('#release-account-confirm').checked}}).catch(e=>notice(e.message,true));
 async function validate(){const r=get();$('#release-validation-state').textContent='Measuring audio and checking release files...';report=await api('/api/release/'+r.id+'/validate');$('#release-validation-state').textContent=report.ready?'All package checks passed. Ready for your review.':report.issues.length+' items need review.';$('#release-validation').innerHTML=report.issues.map(i=>`<button class="release-issue" data-release-issue="${esc(i.view)}">${esc(i.message)}<small>Open ${esc(i.view)}</small></button>`).join('')+(report.measurement?`<p class="hint">Measured audio: ${report.measurement.integratedLUFS} LUFS · ${report.measurement.truePeakDB} dBTP · ${report.duration?.toFixed(2)} seconds</p>`:'');$$('[data-release-issue]').forEach(b=>b.onclick=()=>show(b.dataset.releaseIssue));}
 $('#release-validate').onclick=()=>validate().catch(e=>{notice(e.message,true);$('#release-validation-state').textContent='Validation could not finish.';});
 $('#release-export').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{await save({showNotes:$('#release-show-notes').value});const r=get(),result=await api('/api/release/'+r.id+'/export','POST',{allowIncomplete:$('#release-incomplete').checked});await refresh();$('#release-export-result').innerHTML=`<p>${esc(result.manifest.status==='incomplete-review'?'Incomplete review package saved':'Review package saved')}</p><a class="button" href="/api/project/${r.researchId}/file?name=${encodeURIComponent(result.name)}" download>Download release ZIP</a>`;}catch(e){notice(e.message,true);}finally{b.disabled=false;}};
 window.addEventListener('cts-view',e=>{if(e.detail==='release')load();});
}
