import { mountChapterTools } from '/script-tools.mjs';
import { mountCatalog } from '/catalog.mjs';
import { mountVoiceBooth } from '/voice-booth.mjs';
import { mountConversations } from '/conversation-ui.mjs';
import { mountCampaign } from '/campaign.mjs';
import { mountReleaseDesk } from '/release-desk.mjs';
import { mountMix } from '/mix.mjs';
import { mountRecorder } from '/recorder.mjs';

export function mountRelease(ctx){
  const {api,notice,esc,show,setProject,setEpisode}=ctx,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  let release=null, loading=0,editingClaim=null;const switchGuards=[];
  document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/release.css">');
  $('.rail nav').insertAdjacentHTML('beforebegin','<div class="release-picker"><label for="release-picker">Release project</label><select id="release-picker"><option value="">Choose a release</option></select><button id="release-new">New release project</button></div>');
  $('.rail nav').insertAdjacentHTML('afterbegin','<button data-view="overview">Release overview</button>');
  $('.rail nav').insertAdjacentHTML('beforeend','<button data-view="claims">Sources & claims</button><button data-view="recording">Recording booth</button><button data-view="library">Media library</button>');
  $('main').insertAdjacentHTML('afterbegin','<p id="release-destination" class="release-destination" hidden></p>');
  $('main').insertAdjacentHTML('beforeend',`
    <section class="view" id="view-overview" hidden><div class="section-intro"><h2 id="release-title">One release. Every part together.</h2><p>Your episode, research, recordings and campaign share this project. Choose a stage to keep working.</p></div><div id="release-stages" class="stage-list"><p class="empty">Create a release project or link an existing episode to begin.</p></div><div class="working-panel panel-body"><h3>Production queue</h3><p class="hint">Jobs and logs survive a restart. Failed work is retried only when you request it.</p><div id="durable-jobs"></div></div></section>
    <section class="view" id="view-claims" hidden><div class="section-intro"><h2>Keep the source beside the claim.</h2><p>Attach a source, quotation and review notes. Changing a claim or source resets its verification.</p></div><form id="claim-form" class="working-panel panel-body"><div class="field-pair"><label>Claim belongs to<select id="claim-target"><option value="script">Episode script</option><option value="carousel">Instagram carousel</option></select></label><label>Source link<input type="url" id="claim-source" required placeholder="https://..."></label></div><label>Exact passage<textarea id="claim-text" rows="3" required></textarea></label><label>Source quotation<textarea id="claim-quote" rows="3"></textarea></label><label>Verification notes<textarea id="claim-notes" rows="2"></textarea></label><button class="primary">Attach source</button></form><div id="claim-list"></div></section>
    <section class="view" id="view-library" hidden><div class="section-intro"><h2>Everything this release uses.</h2><p>Search files, tags, folders and rights notes. Uploaded and generated media appear together.</p></div><div class="row actions"><input id="library-search" type="search" placeholder="Search this release" aria-label="Search media"><button id="library-refresh">Refresh library</button><button id="library-duplicates">Find duplicates</button><label class="button">Import files<input id="library-import" type="file" multiple hidden></label></div><p id="library-result" role="status"></p><div id="library-files"></div></section>
    <dialog id="release-create-dialog"><form id="release-create-form"><h2>New release project</h2><label>Release title<input id="release-create-title" required maxlength="200"></label><label>Episode<select id="release-link-episode"><option value="">Start a blank script</option></select></label><label>Research folder<select id="release-link-research"><option value="">Create a research folder</option></select></label><div class="row actions"><button class="primary">Create project</button><button type="button" id="release-create-cancel">Cancel</button></div><p class="hint">Starting a blank project does not use provider credits.</p></form></dialog>
    <dialog id="job-retry-dialog"><h2>Review before retrying</h2><p>The first attempt may have saved outputs or used provider credits. Check its log and files before requesting another attempt.</p><pre id="retry-log"></pre><label class="check-label"><input type="checkbox" id="retry-ack"> I reviewed the outputs. This retry may use credits.</label><div class="row actions"><button id="retry-go" class="primary">Retry job</button><button id="retry-cancel">Cancel</button></div></dialog>`);
  $$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
  function need(){if(!release)throw new Error('Choose a release project first.');return release;}
  async function save(patch){const current=need();const r=await api('/api/release/'+current.id,'PUT',{...patch,expectedRevision:current.revision});if(release?.id!==current.id)return r;release={...release,...r};window.dispatchEvent(new CustomEvent('cts-release-updated',{detail:release}));return release;}
  async function refresh(){if(!release)return;const id=release.id,r=await api('/api/release/'+id);if(release?.id!==id)return;release=r;render();window.dispatchEvent(new CustomEvent('cts-release-updated',{detail:release}));}
  async function select(id){for(const guard of switchGuards)await guard();const seq=++loading;if(window.ctsProduction)await window.ctsProduction.save();const next=id?await api('/api/release/'+id):null;if(seq!==loading)return;await setProject(next?.researchId||'');if(window.ctsProduction)await window.ctsProduction.load(next?.episodeId||'');else await setEpisode(next?.episodeId||'');release=next;document.body.classList.toggle('has-release',Boolean(next));localStorage.setItem('cts-release',id);$('#release-picker').value=id;for(const el of $$('#project,#episode,[data-production-episode]'))el.disabled=Boolean(next);render();window.dispatchEvent(new CustomEvent('cts-release',{detail:release}));}
  async function list(){const items=await api('/api/releases');$('#release-picker').innerHTML='<option value="">Choose a release</option>'+items.map(r=>`<option value="${esc(r.id)}">${esc(r.title)}</option>`).join('');$('#release-picker').value=release?.id||'';}
  $('#release-picker').onchange=()=>select($('#release-picker').value).catch(e=>{notice(e.message,true);$('#release-picker').value=release?.id||'';});
  $('#release-new').onclick=async()=>{try{const [eps,projects]=await Promise.all([api('/api/drafts'),api('/api/projects')]);$('#release-link-episode').innerHTML='<option value="">Start a blank script</option>'+eps.map(r=>`<option value="${esc(r.id)}">${esc(r.title)}</option>`).join('');$('#release-link-research').innerHTML='<option value="">Create a research folder</option>'+projects.map(r=>`<option value="${esc(r.id)}">${esc(r.title)}</option>`).join('');$('#release-create-dialog').showModal();}catch(e){notice(e.message,true);}};
  $('#release-create-cancel').onclick=()=>$('#release-create-dialog').close();
  $('#release-create-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const r=await api('/api/releases','POST',{title:$('#release-create-title').value,episodeId:$('#release-link-episode').value,researchId:$('#release-link-research').value});await list();await select(r.id);$('#release-create-dialog').close();show('overview');}catch(e){notice(e.message,true);}finally{b.disabled=false;}};
  function render(){const r=release;$('#release-destination').hidden=!r;$('#release-destination').textContent=r?`PROJECT / ${r.title} · @${r.account.replace(/^@/,'')}`:'';$('#release-title').textContent=r?.title||'One release. Every part together.';$('#release-stages').innerHTML=r?r.readiness.stages.map(s=>`<button data-stage="${s.view}" class="stage"><span>${esc(s.label)}</span><b>${s.ready?'Ready':'Needs work'}</b><small>${esc(s.ready?'Open workspace':s.reason)}</small></button>`).join(''):'<p class="empty">Create a release project or link an existing episode to begin.</p>';$$('[data-stage]').forEach(b=>b.onclick=()=>show(b.dataset.stage));renderClaims();renderLibrary();}
  $('#claim-form').onsubmit=async e=>{e.preventDefault();try{const r=need();await save({claims:[...r.claims.filter(c=>c.id!==editingClaim),{id:editingClaim||crypto.randomUUID(),target:$('#claim-target').value,text:$('#claim-text').value.trim(),source:$('#claim-source').value.trim(),quote:$('#claim-quote').value,notes:$('#claim-notes').value,verified:false}]});editingClaim=null;e.target.reset();await refresh();}catch(e){notice(e.message,true);}};
  function renderClaims(){if(!release){$('#claim-list').innerHTML='<p class="empty">Choose a release project.</p>';return;}const script=(release.episode?.script||[]).join('\n'),slides=release.carousel.slides.map(s=>s.text||'').join('\n');$('#claim-list').innerHTML=release.claims.map((c,i)=>{const present=(c.target==='carousel'?slides:script).includes(c.text);return `<article class="claim-row"><div><b>${esc(c.text)}</b><p><a href="${esc(c.source)}" target="_blank" rel="noopener">${esc(c.source)}</a></p><blockquote>${esc(c.quote||'No quotation saved')}</blockquote><p>${esc(c.notes)}</p><small>${present?'Passage found':'Passage changed or missing; verification required'}</small></div><label class="check-label"><input type="checkbox" data-claim-verify="${i}" ${c.verified&&present?'checked':''} ${!present?'disabled':''}> Verified against source</label><button data-claim-edit="${i}">Edit claim</button><button data-claim-archive="${i}">Archive claim</button></article>`;}).join('')||'<p class="empty">No source-linked claims yet. Attach the factual passages that need review.</p>';$$('[data-claim-verify]').forEach(el=>el.onchange=async()=>{try{const claims=structuredClone(need().claims);claims[Number(el.dataset.claimVerify)].verified=el.checked;await save({claims});await refresh();}catch(e){notice(e.message,true);}});$$('[data-claim-edit]').forEach(b=>b.onclick=()=>{const c=release.claims[Number(b.dataset.claimEdit)];editingClaim=c.id;$('#claim-target').value=c.target;$('#claim-source').value=c.source;$('#claim-text').value=c.text;$('#claim-quote').value=c.quote;$('#claim-notes').value=c.notes;notice('Edit this passage and attach the revised source. Verification resets when the text or source changes.');});}
  document.addEventListener('click',async e=>{const b=e.target.closest('[data-claim-archive]');if(!b)return;try{const r=need(),index=Number(b.dataset.claimArchive);await save({claims:r.claims.filter((_,i)=>i!==index)});await refresh();notice('Claim archived in project history.');}catch(e){notice(e.message,true);}});
  function renderLibrary(){const q=$('#library-search').value.toLowerCase(),items=(release?.inventory||[]).filter(a=>[a.name,a.folder,...a.tags||[],a.source,a.rights].join(' ').toLowerCase().includes(q));$('#library-files').innerHTML=items.map(a=>`<article class="library-row"><div>${/\.(png|jpe?g|webp)$/i.test(a.name)?`<img src="${esc(a.url)}" alt="${esc(a.name)}" loading="lazy">`:'<span class="file-type">'+esc(a.name.split('.').pop().toUpperCase())+'</span>'}</div><div><a href="${esc(a.url)}" target="_blank" rel="noopener">${esc(a.name)}</a><small>${(a.size/1024/1024).toFixed(2)} MB · ${esc(a.folder||'Unfiled')} · ${esc(a.tags?.join(', ')||'No tags')}</small><p>${esc(a.rights||'Rights note needed')}</p><details><summary>Edit file details</summary><form data-asset-meta="${esc(a.key)}"><label>Folder<input name="folder" value="${esc(a.folder||'')}"></label><label>Tags, separated by commas<input name="tags" value="${esc(a.tags?.join(', ')||'')}"></label><label>Source<input name="source" value="${esc(a.source||'')}"></label><label>Rights / permission<textarea name="rights">${esc(a.rights||'')}</textarea></label><button>Save details</button></form></details><p class="hint">${esc(usage(a.key).join(' · ')||'Not assigned to a composition')} · Version ${a.version||1}${a.supersededBy?' · Previous version retained':''}</p><label class="button">Replace with a new version<input type="file" data-replace-asset="${esc(a.key)}" hidden></label></div></article>`).join('')||'<p class="empty">No matching assets. Import source files or save media from a production tool.</p>';$$('[data-asset-meta]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();try{const data=new FormData(f),assets=structuredClone(need().assets);assets[f.dataset.assetMeta]={...assets[f.dataset.assetMeta],folder:data.get('folder'),tags:String(data.get('tags')).split(',').map(s=>s.trim()).filter(Boolean),source:data.get('source'),rights:data.get('rights')};await save({assets});await refresh();}catch(e){notice(e.message,true);}});}
  document.addEventListener('change',async e=>{if(!e.target.matches('[data-replace-asset]'))return;const el=e.target,file=el.files[0];if(!file)return;try{const r=need(),name='version-'+Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._ -]/g,'-').slice(-75);await api('/api/project/'+r.researchId+'/upload?name='+encodeURIComponent(name),'POST',file);await api('/api/release/'+r.id+'/replace-asset','POST',{oldKey:el.dataset.replaceAsset,newKey:'project:'+r.researchId+':'+name});await refresh();notice('New version linked. Previous file retained; affected compositions need review.');}catch(e){notice(e.message,true);}});
  function usage(key){if(!release)return[];const out=[];if(release.brand.cover===key)out.push('Episode cover');if(release.brand.approved.includes(key))out.push('Approved brand asset');release.carousel.slides.forEach((s,i)=>{if(s.image===key)out.push('Slide '+(i+1));});release.storyboard.scenes.forEach((s,i)=>{if(s.image===key||s.audio===key)out.push('Trailer scene '+(i+1));});release.timeline.tracks.forEach(t=>{if(t.clips?.some(c=>c.asset===key))out.push(t.name);});return out;}
  $('#library-search').oninput=renderLibrary;$('#library-refresh').onclick=()=>refresh().catch(e=>notice(e.message,true));
  $('#library-import').onchange=async e=>{try{const r=need();for(const file of e.target.files){const name='import-'+Date.now()+'-'+crypto.randomUUID().slice(0,6)+'-'+file.name.replace(/[^a-zA-Z0-9._ -]/g,'-').slice(-70);await api(`/api/project/${r.researchId}/upload?name=${encodeURIComponent(name)}`,'POST',file);}await refresh();}catch(e){notice(e.message,true);}finally{e.target.value='';}};
  $('#library-duplicates').onclick=async()=>{try{const groups=await api('/api/release/'+need().id+'/duplicates');$('#library-result').textContent=groups.length?groups.map(g=>g.map(k=>k.split(':').at(-1)).join(' = ')).join('\n'):'No identical files found.';}catch(e){notice(e.message,true);}};
  let retryId=null;
  async function jobs(){const list=await api('/api/jobs');$('#durable-jobs').innerHTML=list.filter(j=>!release||!j.draft||[release.episodeId,release.researchId,...release.postIds].includes(j.draft)).slice(-15).reverse().map(j=>`<details class="activity"><summary>${esc(j.action)} · ${esc(j.state|| (j.done?'Complete':'Working'))}</summary><button data-persisted-log="${esc(j.id)}">Read log</button>${['failed','interrupted'].includes(j.state)?`<button data-retry="${esc(j.id)}">Review retry</button>`:''}<pre></pre></details>`).join('')||'<p class="hint">No production jobs yet.</p>';$$('[data-persisted-log]').forEach(b=>b.onclick=async()=>{const j=await api('/api/job/'+b.dataset.persistedLog);b.parentElement.querySelector('pre').textContent=j.log||'Waiting for output.';});$$('[data-retry]').forEach(b=>b.onclick=async()=>{retryId=b.dataset.retry;const j=await api('/api/job/'+retryId);$('#retry-log').textContent=j.log;$('#retry-ack').checked=false;$('#job-retry-dialog').showModal();});}
  $('#retry-go').onclick=async()=>{try{await api('/api/job/'+retryId+'/retry','POST',{acknowledgeCredits:$('#retry-ack').checked});$('#job-retry-dialog').close();await jobs();}catch(e){notice(e.message,true);}};$('#retry-cancel').onclick=()=>$('#job-retry-dialog').close();
  const kit={...ctx,get:need,save,refresh,usage,onBeforeSwitch:fn=>switchGuards.push(fn)};window.ctsRelease=kit;mountChapterTools(kit);mountRecorder(kit);mountMix(kit);mountCatalog(kit);mountVoiceBooth(kit);mountConversations(kit);mountCampaign(kit);mountReleaseDesk(kit);
  const navigation=$('.rail nav'),extras=[...navigation.children].filter(el=>!el.dataset.view),groups=[['',['overview','assistant']],['Write',['script','documents','claims']],['Audio',['recording','booth','mix','transcript']],['Design',['create','brand','carousel','storyboard']],['Deliver',['library','release']],['',['settings','audio','chat']]];
  for(const [label,views] of groups){if(label){const heading=document.createElement('span');heading.className='nav-group-label';heading.textContent=label;navigation.append(heading);}for(const view of views){const button=navigation.querySelector('[data-view="'+view+'"]');if(button)navigation.append(button);}}for(const el of extras)navigation.append(el);
  window.addEventListener('cts-view',e=>{if(['overview','library','claims'].includes(e.detail))refresh().catch(e=>notice(e.message,true));if(e.detail==='overview')jobs().catch(()=>{});});
  setInterval(()=>{if(!$('#view-overview').hidden)jobs().catch(()=>{});},3000);
  const initialize=()=>list().then(()=>{const id=localStorage.getItem('cts-release');if(id)return select(id);}).catch(e=>notice(e.message,true));
  if(window.ctsWorkspaceReady)initialize();else window.addEventListener('cts-workspace-ready',initialize,{once:true});
}
