import { atomicJson } from './release-store.mjs';
import { join } from 'node:path';
import { publicJob } from './job-queue.mjs';
import { validateTimeline } from './audio-timeline.mjs';
import { conversations,conversation,createConversation,renameConversation,streamConversation } from './conversations.mjs';
import { validateStoryboard } from './trailer-engine.mjs';
import { validateRelease,exportRelease } from './release-package.mjs';
import { mkdir,copyFile,writeFile } from 'node:fs/promises';
export async function releaseRoutes({req,res,p,url,releases,json,readBody,startJob,running}){
  if(p!=='/api/releases'&&!p.startsWith('/api/release/'))return false;
  try{
    if(p==='/api/releases'&&req.method==='GET'){json(res,200,await releases.list());return true;}
    if(p==='/api/releases'&&req.method==='POST'){const body=await readBody(req);if(!body)throw new Error('Invalid release request.');json(res,201,await releases.create(body));return true;}
    const [, , ,id,sub]=p.split('/');
    if(sub==='use-cover'&&req.method==='POST'){const r=await releases.get(id),ep=await releases.episode(r);if(ep.status==='published')throw new Error('Published cover art is locked.');if(running().some(j=>j.draft===r.episodeId))throw new Error('Wait for the current episode job.');if(!r.brand.cover||!r.brand.approved.includes(r.brand.cover))throw new Error('Select approved cover art first.');const {asset}=await releases.assetPath(id,r.brand.cover);if(!/\.(png|jpe?g|webp)$/i.test(asset.name))throw new Error('Choose approved image artwork.');const name='cover-'+Date.now()+'.json';await atomicJson(join(releases.folder(id),name),{asset:r.brand.cover});json(res,202,publicJob(startJob('release-cover',{id,snapshot:name,lockId:r.episodeId})));return true;}
    if(sub==='replace-asset'&&req.method==='POST'){const b=await readBody(req);json(res,200,await releases.replaceAsset(id,b?.oldKey,b?.newKey));return true;}
    if(sub==='validate'&&req.method==='GET'){json(res,200,await validateRelease(releases,id));return true;}
    if(sub==='export'&&req.method==='POST'){const b=await readBody(req);json(res,200,await exportRelease(releases,id,{allowIncomplete:b?.allowIncomplete===true}));return true;}
    if(sub==='carousel-export'&&req.method==='POST'){const b=await readBody(req),r=await releases.get(id);if(!b||b.expectedRevision!==r.revision||!Array.isArray(b.names)||!b.names.length||b.names.length>10||b.names.some(n=>typeof n!=='string'||!/^carousel-\d+-slide-\d+\.jpg$/.test(n)))throw new Error('Save the carousel and export valid rendered slides.');if(b.names.length!==r.carousel.slides.length)throw new Error('Rendered slide count does not match the saved composition.');const postId='campaign-'+Date.now(),dir=join(releases.root,'posts',postId);await mkdir(dir,{recursive:true});for(const [i,name] of b.names.entries()){const source=await releases.assetPath(id,'project:'+r.researchId+':'+name);await copyFile(source.path,join(dir,`slide-${i+1}.jpg`));await copyFile(source.path,join(dir,`composed-${i+1}.jpg`));}await atomicJson(join(dir,'post.json'),{title:r.title,status:'draft',account:r.account,created:new Date().toISOString(),rendered:new Date().toISOString(),caption:r.carousel.caption,slides:r.carousel.slides.map((s,i)=>({kind:'cover',art:`composed-${i+1}.jpg`,text:s.text})),releaseId:r.id});await writeFile(join(dir,'caption.txt'),r.carousel.caption);await releases.update(id,{expectedRevision:r.revision,postIds:[...r.postIds,postId],carousel:{...r.carousel,exportedAt:new Date().toISOString(),exportedPostId:postId}});json(res,201,{id:postId});return true;}
    if(sub==='conversations'){
      const cid=p.split('/')[5],action=p.split('/')[6];
      if(!cid&&req.method==='GET'){json(res,200,await conversations(releases,id));return true;}
      if(!cid&&req.method==='POST'){const b=await readBody(req);json(res,201,await createConversation(releases,id,b?.title));return true;}
      if(cid&&!action&&req.method==='GET'){json(res,200,await conversation(releases,id,cid));return true;}
      if(cid&&!action&&req.method==='PUT'){const b=await readBody(req);json(res,200,await renameConversation(releases,id,cid,b?.title));return true;}
      if(action==='stream'&&req.method==='POST'){const body=await readBody(req);if(!body)throw new Error('Invalid conversation request.');await conversation(releases,id,cid);const controller=new AbortController();res.on('close',()=>controller.abort());res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});const emit=(type,data)=>{if(!res.destroyed)res.write('data: '+JSON.stringify({...data,type})+'\n\n');};try{await streamConversation({store:releases,id,cid,body,signal:controller.signal,emit});}catch(e){emit('complete',{incomplete:true,answer:e.message,error:e.message,actions:[]});}res.end();return true;}
    }
    if(sub==='voice'&&req.method==='POST'){const b=await readBody(req),r=await releases.get(id),ep=await releases.episode(r);if(!b||b.expectedRevision!==r.revision)throw new Error('Reload the project before generating voice.');if(ep.status==='published')throw new Error('Published episode media is locked.');if(running().some(j=>j.draft===r.episodeId))throw new Error('Wait for the current episode job.');if(typeof b.voiceId!=='string'||!b.voiceId||b.voiceId.length>200||typeof b.model!=='string'||!b.model||b.model.length>200)throw new Error('Choose a voice and model.');let chapters;if(b.audition!==null&&b.audition!==undefined){if(typeof b.audition!=='string'||!b.audition.trim()||b.audition.length>450)throw new Error('Auditions need 1 to 450 characters.');chapters=[{index:0,text:b.audition}];}else{if(!Array.isArray(b.chapters)||!b.chapters.length||b.chapters.some(i=>!Number.isInteger(i)||!ep.script?.[i]))throw new Error('Select valid saved chapters.');chapters=[...new Set(b.chapters)].map(index=>({index,text:ep.script[index]}));}const name='voice-'+Date.now()+'.json';await atomicJson(join(releases.folder(id),name),{chapters,voiceId:b.voiceId,model:b.model,voiceSettings:b.voiceSettings||{},audition:b.audition!==null&&b.audition!==undefined,allowUncertain:b.allowUncertain===true});json(res,202,publicJob(startJob('release-voice',{id,snapshot:name,lockId:r.episodeId})));return true;}
    if(sub==='render'&&req.method==='POST'){const b=await readBody(req),r=await releases.get(id);if(!b||b.expectedRevision!==r.revision)throw new Error('Reload the project before rendering.');if(!['mix','trailer'].includes(b.kind))throw new Error('Unsupported renderer.');if(running().some(j=>j.draft===r.episodeId))throw new Error('Wait for the current episode job.');if(b.kind==='mix')validateTimeline(r.timeline);else validateStoryboard(r.storyboard);const name='render-'+Date.now()+'.json';await atomicJson(join(releases.folder(id),name),{timeline:r.timeline,storyboard:r.storyboard,preview:b.preview===true,bypass:b.bypass===true});json(res,202,publicJob(startJob('release-media',{id,kind:b.kind,snapshot:name,lockId:r.episodeId})));return true;}
    if(sub==='use-audio'&&req.method==='POST'){const b=await readBody(req),r=await releases.get(id),ep=await releases.episode(r);if(ep.status==='published')throw new Error('Published media is locked.');if(running().some(j=>j.draft===r.episodeId))throw new Error('Wait for the episode job to finish.');const {path,asset}=await releases.assetPath(id,b?.asset);if(!/\.(wav|mp3|m4a|webm|ogg)$/i.test(asset.name))throw new Error('Select an audio file.');json(res,202,publicJob(startJob('voice',{id:r.episodeId,from:path,noTrim:true,noMusic:true})));return true;}
    if(!sub&&req.method==='GET'){const release=await releases.get(id);json(res,200,{...release,episode:await releases.episode(release),inventory:await releases.inventory(id),readiness:await releases.readiness(id)});return true;}
    if(!sub&&req.method==='PUT'){const b=await readBody(req);if(!b)throw new Error('Invalid release changes.');json(res,200,await releases.update(id,b));return true;}
    if(sub==='duplicates'&&req.method==='GET'){json(res,200,await releases.duplicates(id));return true;}
    json(res,404,{error:'Unknown release operation.'});
  }catch(e){json(res,400,{error:e.message});}return true;
}
