import { readFile,writeFile,stat } from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { captionText } from './audio-timeline.mjs';
import { measureAudio,probe } from './media-engine.mjs';

const crcTable=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
const crc32=b=>{let crc=0xffffffff;for(const n of b)crc=crcTable[(crc^n)&255]^(crc>>>8);return(crc^0xffffffff)>>>0;};
// Standard ZIP, stored entries. No shell paths or external archive dependency.
export function zipFiles(entries){const chunks=[],central=[];let offset=0;for(const entry of entries){const name=Buffer.from(entry.name),data=Buffer.isBuffer(entry.data)?entry.data:Buffer.from(entry.data),crc=crc32(data),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0x800,6);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(name.length,26);chunks.push(local,name,data);const header=Buffer.alloc(46);header.writeUInt32LE(0x02014b50,0);header.writeUInt16LE(20,4);header.writeUInt16LE(20,6);header.writeUInt16LE(0x800,8);header.writeUInt32LE(crc,16);header.writeUInt32LE(data.length,20);header.writeUInt32LE(data.length,24);header.writeUInt16LE(name.length,28);header.writeUInt32LE(offset,42);central.push(header,name);offset+=local.length+name.length+data.length;}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...chunks,directory,end]);}
export async function validateRelease(store,id){const r=await store.get(id),ep=await store.episode(r),inventory=await store.inventory(id),readiness=await store.readiness(id),issues=[];const add=(view,message)=>issues.push({view,message});if(!ep.slug)add('release','Episode needs a valid publishing slug.');if((ep.script||[]).some(s=>s.trim())&&!r.claims.length)add('claims','Attach sources for factual script passages before release review.');
 for(const s of readiness.stages)if(!s.ready)add(s.view,s.reason);
 const audio=inventory.find(a=>a.type==='draft'&&a.name==='episode.mp3');let measurement=null,audioMeta=null;if(audio&&r.timeline.changedAt&&audio.modified<r.timeline.changedAt)add('mix','Timeline changed after the episode master. Render and review a fresh master.');if(!audio)add('mix','Choose a finished mix and use it as episode narration.');else{try{const {path}=await store.assetPath(id,audio.key);audioMeta=await probe(path);if(Number(audioMeta.format.duration)<1200)add('mix','Podcast episodes must be at least 20 minutes. Short clips belong in the trailer and Instagram exports.');measurement=await measureAudio(path);if(!Number.isFinite(measurement.integratedLUFS)||measurement.integratedLUFS< -20||measurement.integratedLUFS> -12)add('mix','Master loudness is outside the -20 to -12 LUFS review range.');if(measurement.truePeakDB> -1)add('mix','Audio true peak exceeds -1 dBTP. Review mastering.');}catch(e){add('mix',e.message);}}
 if(r.brand.cover){try{const {path}=await store.assetPath(id,r.brand.cover),meta=await probe(path),s=meta.streams.find(s=>s.codec_type==='video');if(!s||s.width!==s.height||s.width<1400||s.width>3000)add('brand','Podcast cover needs a square image from 1400 to 3000 pixels.');}catch(e){add('brand',e.message);}}
 if(!r.transcript)add('transcript','Load and review the transcript.');else{if(audio&&r.transcript.audioModified&&r.transcript.audioModified!==audio.modified)add('transcript','Episode audio changed after transcript alignment was reviewed.');if(r.transcript.stale)add('transcript','Transcript alignment is stale.');try{captionText(r.transcript.segments);if(audioMeta&&r.transcript.segments.some(s=>s.end>Number(audioMeta.format.duration)+.1))add('transcript','Caption timing extends past the episode audio.');}catch(e){add('transcript',e.message);}}
 const postAssets=inventory.filter(a=>a.type==='post'&&a.id===r.carousel.exportedPostId&&/^slide-\d+\.jpg$/.test(a.name));if(!postAssets.length)add('carousel','Export the reviewed carousel into Instagram drafts.');for(const a of postAssets){const meta=await probe((await store.assetPath(id,a.key)).path);const s=meta.streams[0];if(s.width!==1080||s.height!==1350)add('carousel','Carousel dimensions must be 1080 by 1350.');}
 const trailers=inventory.filter(a=>/^trailer-full-.*\.mp4$/.test(a.name));let currentTrailer=false;for(const a of trailers){try{const info=JSON.parse(await readFile((await store.assetPath(id,a.key+'.json')).path,'utf8'));if(JSON.stringify(info.storyboard)===JSON.stringify(r.storyboard))currentTrailer=true;}catch{}}if(!currentTrailer)add('storyboard','Render a full trailer from the current storyboard.');
 if(!r.releaseReview.accountConfirmed)add('release','Confirm the intended Instagram account in release review.');
 return{ready:issues.length===0,issues,measurement,duration:Number(audioMeta?.format?.duration)||null,account:r.account,checkedAt:new Date().toISOString(),revision:r.revision};
}
export async function exportRelease(store,id,{allowIncomplete=false}={}){const r=await store.get(id),report=await validateRelease(store,id);if(!report.ready&&!allowIncomplete)throw new Error('Resolve the release checklist or explicitly export an incomplete review package.');const ep=await store.episode(r),inventory=await store.inventory(id),selected=inventory.filter(a=>a.type==='draft'&&a.name==='episode.mp3'||a.key===r.brand.cover||a.type==='post'&&/^slide-\d+\.jpg$/.test(a.name)||/^trailer-full-.*\.mp4$/.test(a.name));const total=selected.reduce((n,a)=>n+a.size,0);if(total>750*1024*1024)throw new Error('This package exceeds 750 MB. Export media individually from the library.');
 const entries=[{name:'script.md',data:'# '+ep.title+'\n\n'+(ep.script||[]).join('\n\n')},{name:'show-notes.md',data:r.showNotes},{name:'instagram-caption.txt',data:r.carousel.caption},{name:'sources.json',data:JSON.stringify(r.claims,null,2)},{name:'project.json',data:JSON.stringify(r,null,2)}];
 if(r.transcript){entries.push({name:'transcript.json',data:JSON.stringify(r.transcript,null,2)});if(!r.transcript.stale)entries.push({name:'captions.srt',data:captionText(r.transcript.segments)});}
 for(const a of selected){const {path}=await store.assetPath(id,a.key);entries.push({name:a.type==='post'?`instagram/${a.id}/${a.name}`:a.key===r.brand.cover?'cover/'+a.name:a.name,data:await readFile(path)});}
 const manifest={project:r.title,id,exportedAt:new Date().toISOString(),status:report.ready?'ready-for-review':'incomplete-review',published:false,report,files:entries.map(e=>({name:e.name,bytes:Buffer.byteLength(e.data),sha256:createHash('sha256').update(e.data).digest('hex')}))};entries.push({name:'manifest.json',data:JSON.stringify(manifest,null,2)});const name=`release-package-${Date.now()}.zip`;await writeFile(join(store.root,'projects',r.researchId,name),zipFiles(entries));return{name,manifest};
}
