const split=text=>text.split(/\n\s*---\s*\n/).map(s=>s.trim());
export function mountChapterTools({api,notice,esc,get,save}){
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],body=$('#script-body');let selected=0,drag=null,proposal=null;
 body.insertAdjacentHTML('beforebegin',`<div class="chapter-tools"><div id="script-recovery" class="recovery-banner" hidden><span>A recovery draft is available.</span> <button id="recover-script">Review recovery</button><button id="discard-recovery">Discard recovery copy</button></div><div id="chapter-outline" class="chapter-outline" aria-label="Chapter outline"></div><div class="chapter-toolbar"><button id="chapter-add">Add chapter</button><button id="chapter-up">Move chapter up</button><button id="chapter-down">Move chapter down</button><label>Target minutes <input id="chapter-target" type="number" min="0.1" max="60" step="0.5" value="3"></label><button id="chapter-target-save">Save target</button><span id="chapter-details" class="hint"></span></div><div class="chapter-toolbar"><input id="script-find" aria-label="Find text" placeholder="Find text"><input id="script-replace" aria-label="Replacement text" placeholder="Replace with"><button id="script-find-next">Find next</button><button id="script-replace-one">Replace selection</button></div><div class="chapter-toolbar"><input id="passage-instruction" aria-label="Edit instruction" placeholder="Instruction for selected passage"><button id="passage-rewrite">Propose passage edit</button></div></div>`);
 document.body.insertAdjacentHTML('beforeend','<dialog id="passage-dialog"><h2>Review the passage edit</h2><div class="compare-grid"><div><h3>Before</h3><div class="compare-copy" id="passage-before"></div></div><div><h3>Proposed</h3><div class="compare-copy" id="passage-after"></div></div></div><div class="row actions"><button id="passage-apply" class="primary">Apply to selection</button><button id="passage-cancel">Keep original</button></div></dialog>');
 function id(){return window.ctsProduction?.current()?.id;}
 function key(){return 'cts-script-recovery:'+id();}
 function editable(){if(!id()||body.disabled)throw new Error('Choose an unpublished episode first.');}
 function changed(){body.dispatchEvent(new Event('input',{bubbles:true}));outline();}
 function recover(){if(!id())return;try{localStorage.setItem(key(),JSON.stringify({title:$('#script-title').value,script:body.value,caption:$('#script-caption').value,at:Date.now(),base:window.ctsProduction.current().edited||null}));}catch{notice('Recovery storage is full. Save or export the script now.',true);}}
 for(const el of [body,$('#script-title'),$('#script-caption')])el.addEventListener('input',()=>{recover();outline();});
 function outline(){const chapters=split(body.value);selected=Math.min(selected,chapters.length-1);$('#chapter-outline').innerHTML=chapters.map((s,i)=>`<button draggable="true" data-chapter="${i}" ${i===selected?'aria-current="true"':''}>${i+1}. ${esc(s.split('\n')[0].slice(0,35)||'Untitled chapter')}</button>`).join('');$$('[data-chapter]').forEach(b=>{b.onclick=()=>{selected=Number(b.dataset.chapter);let from=0;for(let i=0;i<selected;i++)from+=chapters[i].length+7;body.focus();body.setSelectionRange(from,from+chapters[selected].length);outline();};b.ondragstart=()=>drag=Number(b.dataset.chapter);b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();move(drag,Number(b.dataset.chapter));drag=null;};});const words=(chapters[selected]||'').split(/\s+/).filter(Boolean).length;$('#chapter-details').textContent=`Chapter ${selected+1}: ${words} words · ${(words/166).toFixed(1)} min`;try{$('#chapter-target').value=get().chapterMeta[selected]?.minutes||3;}catch{}}
 function move(from,to){try{editable();const chapters=split(body.value);if(from===null||to<0||to>=chapters.length)return;chapters.splice(to,0,chapters.splice(from,1)[0]);body.value=chapters.join('\n\n---\n\n');selected=to;changed();}catch(e){notice(e.message,true);}}
 $('#chapter-add').onclick=()=>{try{editable();body.value+='\n\n---\n\nNew chapter';selected=split(body.value).length-1;changed();}catch(e){notice(e.message,true);}};
 $('#chapter-up').onclick=()=>move(selected,selected-1);$('#chapter-down').onclick=()=>move(selected,selected+1);
 $('#chapter-target-save').onclick=async()=>{try{const minutes=Number($('#chapter-target').value);if(!Number.isFinite(minutes)||minutes<=0||minutes>60)throw new Error('Choose a target from 0.1 to 60 minutes.');const chapterMeta=[...get().chapterMeta];chapterMeta[selected]={minutes};await save({chapterMeta});notice('Chapter target saved.');}catch(e){notice(e.message,true);}};
 $('#script-find-next').onclick=()=>{const q=$('#script-find').value;if(!q)return;let at=body.value.indexOf(q,body.selectionEnd);if(at<0)at=body.value.indexOf(q);if(at<0)return notice('Text not found.');body.focus();body.setSelectionRange(at,at+q.length);};
 $('#script-replace-one').onclick=()=>{try{editable();if(body.selectionStart===body.selectionEnd)throw new Error('Select text or use Find next first.');body.setRangeText($('#script-replace').value,body.selectionStart,body.selectionEnd,'select');changed();}catch(e){notice(e.message,true);}};
 $('#recover-script').onclick=()=>{try{editable();const r=JSON.parse(localStorage.getItem(key()));proposal={kind:'recovery',original:body.value,after:r.script,recovery:r};$('#passage-before').textContent=body.value;$('#passage-after').textContent=r.script;$('#passage-dialog').showModal();}catch(e){notice(e.message,true);}};
 $('#discard-recovery').onclick=()=>{localStorage.removeItem(key());$('#script-recovery').hidden=true;};
 $('#passage-rewrite').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{editable();const start=body.selectionStart,end=body.selectionEnd,text=body.value.slice(start,end),instruction=$('#passage-instruction').value.trim();if(!text||!instruction)throw new Error('Select a passage and enter an editing instruction.');const original=body.value;const result=await api('/api/passage-edit','POST',{text,instruction,provider:$('#assistant-provider').value});proposal={original,start,end,after:result.text};$('#passage-before').textContent=text;$('#passage-after').textContent=result.text;$('#passage-dialog').showModal();}catch(e){notice(e.message,true);}finally{button.disabled=false;}};
 $('#passage-cancel').onclick=()=>$('#passage-dialog').close();$('#passage-apply').onclick=()=>{try{editable();if(!proposal||body.value!==proposal.original)throw new Error('The script changed. Request a new comparison.');if(proposal.kind==='recovery'){body.value=proposal.after;$('#script-title').value=proposal.recovery.title;$('#script-caption').value=proposal.recovery.caption;}else body.setRangeText(proposal.after,proposal.start,proposal.end,'select');changed();$('#passage-dialog').close();notice('Edit applied to the editor. Save the script when ready.');}catch(e){notice(e.message,true);}};
 window.addEventListener('cts-script-loaded',()=>{selected=0;outline();let recovery;try{recovery=JSON.parse(localStorage.getItem(key()));}catch{}$('#script-recovery').hidden=!recovery||recovery.script===body.value&&recovery.title===$('#script-title').value&&recovery.caption===$('#script-caption').value;});
 window.addEventListener('cts-script-saved',()=>{localStorage.removeItem(key());$('#script-recovery').hidden=true;});
 outline();
}
