import { mkdir,writeFile,copyFile } from 'node:fs/promises';
import { join } from 'node:path';
import { processMedia,probe } from './media-engine.mjs';
export function validateStoryboard(s){if(!s||!Array.isArray(s.scenes)||!s.scenes.length||s.scenes.length>30||!['portrait','landscape'].includes(s.format))throw new Error('Add 1 to 30 trailer scenes and choose a format.');for(const c of s.scenes)if(typeof c.image!=='string'||typeof c.audio!=='string'||!Number.isFinite(c.in)||!Number.isFinite(c.out)||c.in<0||c.out<=c.in||c.out-c.in>90||String(c.caption||'').length>240)throw new Error('Check each scene source, duration and caption.');if(s.music&&(!Number.isFinite(s.musicGain)||s.musicGain>0||s.musicGain< -60))throw new Error('Music volume must be -60 to 0 dB.');if(String(s.endCard||'').length>160)throw new Error('Keep the end card under 160 characters.');return s;}
const wrap=(text,limit)=>String(text||'').split(/\s+/).flatMap(w=>w.match(new RegExp('.{1,'+limit+'}','g'))||[]).reduce((lines,w)=>{if(!lines.length||lines.at(-1).length+w.length+1>limit)lines.push(w);else lines[lines.length-1]+=' '+w;return lines;},[]).join('\n');
export async function renderTrailer(store,r,storyboard,output,{preview=false}={}){
 validateStoryboard(storyboard);const work=join(store.folder(r.id),'trailer-'+Date.now());await mkdir(work,{recursive:true});await copyFile('C:/Windows/Fonts/arial.ttf',join(work,'font.ttf'));
 const [width,height]=storyboard.format==='portrait'?[1080,1920]:[1920,1080],scenes=preview?storyboard.scenes.slice(0,1):storyboard.scenes,files=[];
 for(const [i,scene] of scenes.entries()){
  if(!r.brand.approved.includes(scene.image))throw new Error('Approve each storyboard visual in the brand kit first.');
  const visual=await store.assetPath(r.id,scene.image),audio=await store.assetPath(r.id,scene.audio),meta=await probe(audio.path);if(scene.out>Number(meta.format.duration)+.001)throw new Error('Scene '+(i+1)+' extends past its audio source.');
  const video=/\.(mp4|webm)$/i.test(visual.asset.name),duration=preview?Math.min(10,scene.out-scene.in):scene.out-scene.in;
  const vf=scene.fit==='cover'?`scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height}`:`scale=${width}:${height}:force_original_aspect_ratio=decrease,pad=${width}:${height}:(ow-iw)/2:(oh-ih)/2:black`;
  const caption=wrap(scene.caption,storyboard.format==='portrait'?30:58);await writeFile(join(work,`caption-${i}.txt`),caption);
  const text=caption?`,drawtext=fontfile=font.ttf:textfile=caption-${i}.txt:fontsize=48:fontcolor=white:line_spacing=12:x=(w-tw)/2:y=h-th-${storyboard.format==='portrait'?180:90}:box=1:boxcolor=black@0.8:boxborderw=24`:'';
  const name=`scene-${i}.mp4`;await processMedia('ffmpeg',['-hide_banner','-y','-loglevel','error',...(video?['-stream_loop','-1']:['-loop','1']),'-i',visual.path,'-ss',String(scene.in),'-i',audio.path,'-filter_complex',`[0:v]${vf},setsar=1${text}[v];[1:a]atrim=duration=${duration},asetpts=PTS-STARTPTS,aresample=48000[a]`,'-map','[v]','-map','[a]','-t',String(duration),'-r','30','-c:v','libx264','-preset','fast','-pix_fmt','yuv420p','-c:a','aac','-ar','48000','-ac','2',name],{cwd:work});files.push(name);console.log(`Trailer scene ${i+1} of ${scenes.length} rendered.`);
 }
 if(storyboard.endCard&&!preview){await writeFile(join(work,'end.txt'),wrap(storyboard.endCard,storyboard.format==='portrait'?28:50));await processMedia('ffmpeg',['-hide_banner','-y','-loglevel','error','-f','lavfi','-i',`color=c=0x080809:s=${width}x${height}:r=30:d=3`,'-f','lavfi','-i','anullsrc=r=48000:cl=stereo','-vf','drawtext=fontfile=font.ttf:textfile=end.txt:fontsize=64:fontcolor=white:line_spacing=18:x=(w-tw)/2:y=(h-th)/2','-t','3','-c:v','libx264','-preset','fast','-pix_fmt','yuv420p','-c:a','aac','end.mp4'],{cwd:work});files.push('end.mp4');}
 await writeFile(join(work,'scenes.txt'),files.map(f=>`file '${f}'`).join('\n'));const combined=storyboard.music?join(work,'combined.mp4'):output;await processMedia('ffmpeg',['-hide_banner','-y','-loglevel','error','-f','concat','-safe','1','-i','scenes.txt','-c','copy','-movflags','+faststart',combined],{cwd:work});
 if(storyboard.music){const music=await store.assetPath(r.id,storyboard.music);await processMedia('ffmpeg',['-hide_banner','-y','-loglevel','error','-i',combined,'-stream_loop','-1','-i',music.path,'-filter_complex',`[1:a]volume=${storyboard.musicGain}dB[m];[0:a][m]amix=inputs=2:duration=first:normalize=0[a]`,'-map','0:v','-map','[a]','-c:v','copy','-c:a','aac','-movflags','+faststart',output]);}
 return{width,height,duration:Number((await probe(output)).format.duration)};
}
