export function mountVoiceBooth({api,notice,esc,get,refresh,save,show}){
 const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let ep=null;
 $('.rail nav').insertAdjacentHTML('beforeend','<button data-view="booth">Voice booth</button>');
 $('main').insertAdjacentHTML('beforeend',`<section class="view" id="view-booth" hidden><div class="section-intro"><h2>Direct the voice, chapter by chapter.</h2><p>Audition a short passage, then generate the selected chapters. Completed sections are cached for reuse.</p></div><div class="field-pair"><div class="working-panel panel-body"><label>ElevenLabs voice<select id="booth-voice"><option value="">Load your voices</option></select></label><button id="booth-voices">Load available voices</button><label>Voice model ID<input id="booth-model" value="eleven_multilingual_v2"></label><div class="field-pair">${[['stability','Stability',0,1,.5],['similarity_boost','Similarity',0,1,.75],['style','Style',0,1,0],['speed','Speed',.7,1.2,1]].map(([id,label,min,max,value])=>`<label>${label}<input data-voice-control="${id}" type="number" min="${min}" max="${max}" step="0.05" value="${value}"></label>`).join('')}</div><p class="hint">Eleven v3 uses its supported stability settings; other controls are omitted for that model.</p><button id="booth-remember">Remember voice and controls</button><h3>Audition passage</h3><textarea id="booth-audition" rows="4" maxlength="450" placeholder="Up to 450 characters"></textarea><button id="booth-preview">Generate audition</button></div><div class="working-panel panel-body"><h3>Saved script chapters</h3><div id="booth-chapters"></div><p id="booth-count" role="status"></p><label class="check-label"><input id="booth-retry-uncertain" type="checkbox"> Retry any uncertain requests; this may use credits again</label><button class="primary" id="booth-generate">Generate selected chapters</button><p class="hint">Review the voice, model and character count before generation. Select only the chapters you need.</p><button id="booth-transcribe">Transcribe episode with Deepgram</button><a class="button spaced" href="#transcript" id="booth-open-transcript">Edit transcript & captions</a></div></div><h3>Saved voice takes</h3><div id="booth-results"></div></section>`);
 $('[data-view="booth"]').onclick=()=>show('booth');$('#booth-open-transcript').onclick=e=>{e.preventDefault();show('transcript');};
 async function voices(){const s=await api('/api/settings'),p=s.providers.find(p=>p.id==='elevenlabs'),r=await api('/api/settings/test','POST',{provider:'elevenlabs'});$('#booth-voice').innerHTML='<option value="">Choose your voice</option>'+(r.voices||[]).map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('');$('#booth-voice').value=get().voiceBooth?.voiceId||p.values.voiceId;$('#booth-model').value=get().voiceBooth?.model||s.taskDefaults?.narration?.model||p.values.model;}
 async function load(){const r=get();ep=await api('/api/draft/'+r.episodeId);$('#booth-chapters').innerHTML=(ep.script||[]).map((s,i)=>`<label class="check-label"><input type="checkbox" data-booth-chapter="${i}" checked> Chapter ${i+1} · ${s.length.toLocaleString()} characters</label>`).join('');$$('[data-booth-chapter]').forEach(el=>el.onchange=count);const config=r.voiceBooth;if(config){$('#booth-model').value=config.model;$$('[data-voice-control]').forEach(el=>el.value=config.voiceSettings?.[el.dataset.voiceControl]??el.value);}count();$('#booth-results').innerHTML=r.inventory.filter(a=>/^voice-(chapter|audition)-/.test(a.name)).map(a=>`<div class="take-row"><b>${esc(a.name)}</b><audio src="${esc(a.url)}" controls preload="metadata"></audio><a href="${esc(a.url)}" download>Download take</a></div>`).join('')||'<p class="empty">Generated takes will appear here and in the media library.</p>';}
 function count(){const total=$$('[data-booth-chapter]:checked').reduce((sum,el)=>sum+(ep?.script[Number(el.dataset.boothChapter)]?.length||0),0);$('#booth-count').textContent=total.toLocaleString()+' characters selected · uses ElevenLabs credits';}
 function config(){return{voiceId:$('#booth-voice').value,model:$('#booth-model').value,voiceSettings:Object.fromEntries($$('[data-voice-control]').map(el=>[el.dataset.voiceControl,Number(el.value)]))};}
 $('#booth-voices').onclick=()=>voices().catch(e=>notice(e.message,true));$('#booth-remember').onclick=async()=>{try{const c=config();if(!c.voiceId)throw new Error('Choose a voice first.');await save({voiceBooth:c});await api('/api/settings','PUT',{provider:'elevenlabs',voiceId:c.voiceId,model:c.model});notice('Voice selection remembered for this release.');}catch(e){notice(e.message,true);}};
 async function generate(audition){const r=get(),c=config();if(!c.voiceId)throw new Error('Choose an available voice.');const chapters=$$('[data-booth-chapter]:checked').map(el=>Number(el.dataset.boothChapter));await api('/api/release/'+r.id+'/voice','POST',{...c,chapters,audition:audition?$('#booth-audition').value:null,allowUncertain:$('#booth-retry-uncertain').checked,expectedRevision:r.revision});notice('Voice generation queued. Cached sections will be reused.');}
 $('#booth-preview').onclick=()=>generate(true).catch(e=>notice(e.message,true));$('#booth-generate').onclick=()=>generate(false).catch(e=>notice(e.message,true));$('#booth-transcribe').onclick=async()=>{try{await api('/api/run','POST',{action:'deepgram',id:get().episodeId});notice('Deepgram transcription queued. Open the transcript after completion.');}catch(e){notice(e.message,true);}};
 window.addEventListener('cts-view',e=>{if(e.detail==='booth')load().catch(e=>notice(e.message,true));});window.addEventListener('cts-release-updated',()=>{if(!$('#view-booth').hidden)load().catch(()=>{});});
}
