import { mountRelease } from '/release.mjs';
import { mountProduction } from '/production.mjs';
import { editPCM, wavBytes } from '/audio-edit.mjs';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc = encodeURIComponent;
let project = null, episode = null, dirty = false, busyChat = false, audioBuffer = null, audioContext, audioURL, audioName = 'audio', projectSeq = 0, episodeSeq = 0;
let selectedProject = localStorage.getItem('cts-desk-project') || '', selectedEpisode = localStorage.getItem('cts-desk-episode') || '';
const drafts = new Map();
let peaks = null;
async function api(url, method = 'GET', body) {
  const raw = body instanceof Blob;
  const response = await fetch(url, { method, headers: { 'X-CTS':'1', ...(!raw && body !== undefined ? {'Content-Type':'application/json'} : {}) }, body: body === undefined ? undefined : raw ? body : JSON.stringify(body) });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'The request could not finish.');
  return data;
}
let noticeTimer;
function notice(message, bad = false) { $('#notice').textContent = message; $('#notice').className = bad ? 'bad' : ''; $('#notice').hidden = false; clearTimeout(noticeTimer); noticeTimer = setTimeout(() => $('#notice').hidden = true, bad ? 12000 : 6000); }
function bind(id, fn) { $(id).addEventListener('click', async e => { const button = e.currentTarget; button.disabled = true; try { await fn(e); } catch (e) { notice(e.message, true); } finally { button.disabled = false; } }); }
function needProject() { if (!project) throw new Error('Choose or create a research folder first.'); return project.id; }
function needEpisode() { if (!episode) throw new Error('Choose an episode first.'); return episode.id; }
function fileURL(type, id, name) { return `/api/${type}/${enc(id)}/file?name=${enc(name)}`; }
function uniqueName(name) { const dot = name.lastIndexOf('.'); const ext = dot > 0 ? name.slice(dot).replace(/[^a-zA-Z0-9.]/g, '').slice(0,12) : ''; const base = (dot > 0 ? name.slice(0,dot) : name).replace(/[^a-zA-Z0-9 _-]/g,'-').replace(/^[ -]+/,'').slice(0,65) || 'document'; return `${base}-${Date.now().toString(36)}-${crypto.randomUUID().slice(0,6)}${ext}`; }
function download(blob, name) { const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),60000); }
function askName(title) { const dialog=$('#name-dialog'); $('#dialog-title').textContent=title; $('#new-name').value=''; dialog.returnValue='cancel'; dialog.showModal(); $('#new-name').focus(); return new Promise(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue==='save' ? $('#new-name').value.trim() : null),{once:true})); }
function show(view) { const valid=Boolean(document.getElementById('view-'+view)) ? view : 'create'; $$('.view').forEach(el=>el.hidden=el.id!==`view-${valid}`); $$('[data-view]').forEach(b=>b.toggleAttribute('aria-current',b.dataset.view===valid)); $('#heading').textContent={create:'Create media',audio:'Audio editor',documents:'Documents',chat:'Workspace chat',assistant:'Production chat',script:'Script editor',settings:'Provider settings'}[valid]||({overview:'Release overview',claims:'Sources & claims',recording:'Recording booth',library:'Media library',mix:'Audio timeline',transcript:'Transcript',brand:'Brand kit',carousel:'Instagram composer',storyboard:'Trailer storyboard',release:'Release desk',booth:'Voice booth'})[valid]||valid; history.replaceState(null,'',`#${valid}`); if(valid==='audio') drawWave(); window.dispatchEvent(new CustomEvent('cts-view',{detail:valid})); }
$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));
$('#focus').onclick=()=>document.body.classList.toggle('focus');
document.addEventListener('keydown', e=>{ if(e.key==='Escape')document.body.classList.remove('focus'); if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();if(location.hash==='#script'){window.dispatchEvent(new Event('cts-save-script'));return;}saveNotes().catch(e=>notice(e.message,true));} });
window.addEventListener('beforeunload', e=>{ if(dirty||busyChat){e.preventDefault();e.returnValue='';} });
async function listProjects() { const items=await api('/api/projects'); $('#project').innerHTML='<option value="">Choose a folder</option>'+items.map(p=>`<option value="${esc(p.id)}">${esc(p.title)}</option>`).join(''); if(items.some(p=>p.id===selectedProject))$('#project').value=selectedProject; }
async function loadProject(id, preserveNotes=false) {
  const seq=++projectSeq; const next=id ? await api(`/api/project/${enc(id)}`) : null;
  if(seq!==projectSeq)return;
  project=next; selectedProject=id; localStorage.setItem('cts-desk-project',id);
  if(!preserveNotes){$('#notes').value=project?.notes||'';dirty=false;}
  $('#notes').disabled=!project; ['#save-notes','#download-notes','#save-document'].forEach(s=>$(s).disabled=!project);
  $('#save-state').textContent=project ? dirty ? 'Unsaved changes' : 'Saved in this folder' : 'Choose a research folder';
  renderFiles(); renderChat(); renderAssets();
}
$('#project').onchange=async()=>{const id=$('#project').value; try{if(dirty)await saveNotes();if(busyChat)throw new Error('Wait for the current answer before switching folders.');await loadProject(id);}catch(e){$('#project').value=selectedProject;notice(e.message,true);}};
bind('#new-project',async()=>{if(busyChat)throw new Error('Wait for the current answer before creating a folder.'); if(dirty)await saveNotes(); const title=await askName('New research folder');if(!title)return;const p=await api('/api/projects','POST',{title});selectedProject=p.id;await listProjects();await loadProject(p.id);notice('Research folder created.');});
$('#notes').oninput=()=>{dirty=true;$('#save-state').textContent='Unsaved changes';};
async function saveNotes(){const id=needProject(),text=$('#notes').value;await api(`/api/project/${enc(id)}/notes`,'PUT',{text});if(project?.id===id){project.notes=text;dirty=$('#notes').value!==text;$('#save-state').textContent=dirty?'Unsaved changes':'Saved just now';}}
bind('#save-notes',async()=>{await saveNotes();notice('Notes saved.');});
bind('#download-notes',()=>{needProject();download(new Blob([$('#notes').value],{type:'text/markdown'}),`${project.id}-notes.md`);});
bind('#save-document',async()=>{const id=needProject(),text=$('#notes').value;const title=await askName('Save a separate Markdown document');if(!title)return;const name=uniqueName(title+'.md');await api(`/api/project/${enc(id)}/upload?name=${enc(name)}`,'POST',new Blob([text],{type:'text/markdown'}));await refreshProject();notice(`Saved ${name}`);});
async function refreshProject(){if(project)await loadProject(project.id,true);}
function renderFiles(){ $('#files').innerHTML=project ? project.files.length ? project.files.map(f=>`<div class="file-row"><a href="${fileURL('project',project.id,f.name)}" target="_blank" rel="noopener">${esc(f.name)}</a><small>${(f.size/1024).toFixed(1)} KB</small></div>`).join('') : '<p class="empty">No files yet. Add source PDFs, recordings or images.</p>' : 'Choose a research folder.'; }
async function uploadFiles(files){const id=needProject();for(const file of files){if(file.size>200*1024*1024)throw new Error(`${file.name} exceeds the 200 MB upload limit.`);const name=uniqueName(file.name);await api(`/api/project/${enc(id)}/upload?name=${enc(name)}`,'POST',file);}await refreshProject();notice(`${files.length} file(s) saved to the folder.`);}
$('#file-upload').onchange=async e=>{try{await uploadFiles([...e.target.files]);}catch(e){notice(e.message,true);}finally{e.target.value='';}};
$('#view-documents').addEventListener('dragover',e=>{e.preventDefault();document.body.classList.add('dragging');});
$('#view-documents').addEventListener('dragleave',()=>document.body.classList.remove('dragging'));
$('#view-documents').addEventListener('drop',async e=>{e.preventDefault();document.body.classList.remove('dragging');try{await uploadFiles([...e.dataTransfer.files]);}catch(e){notice(e.message,true);}});
bind('#open-folder',()=>api(`/api/project/${enc(needProject())}/open`,'POST',{}));
function renderChat(){const history=project?.chat||[];$('#messages').innerHTML=history.length ? history.map((m,i)=>`<article class="message user"><div class="who">YOU</div><div class="text">${esc(m.q)}</div></article><article class="message"><div class="who">WORKSPACE ASSISTANT</div><div class="text">${esc(m.a)}</div>${m.skipped?.length?`<p class="hint">Not included: ${esc(m.skipped.join(', '))}</p>`:''}<button data-answer="${i}">Save answer to notes</button></article>`).join('') : `<p class="empty">${project?'Ask a question about this folder. Add source files or notes to give the assistant material to work with.':'Choose or create a research folder to start a conversation.'}</p>`;$$('[data-answer]').forEach(b=>b.onclick=async()=>{try{const entry=project.chat[Number(b.dataset.answer)];$('#notes').value+=`\n\n## ${entry.q}\n\n${entry.a}\n`;dirty=true;await saveNotes();notice('Answer saved to folder notes.');}catch(e){notice(e.message,true);}});$('#messages').scrollTop=$('#messages').scrollHeight;}
$$('[data-question]').forEach(b=>b.onclick=()=>{$('#question').value=b.dataset.question;$('#question').focus();});
$('#chat-form').onsubmit=async e=>{e.preventDefault();if(busyChat)return;try{const id=needProject(),question=$('#question').value.trim();if(!question)throw new Error('Write a question first.');if(dirty)await saveNotes();busyChat=true;$('#send').disabled=true;$('#send').textContent='Reading folder...';await api(`/api/project/${enc(id)}/chat`,'POST',{question});$('#question').value='';await refreshProject();}catch(e){notice(e.message,true);}finally{busyChat=false;$('#send').disabled=false;$('#send').textContent='Send message';}};
async function loadEpisode(id){const seq=++episodeSeq;const next=id?await api(`/api/draft/${enc(id)}`):null;if(seq!==episodeSeq)return;episode=next;selectedEpisode=id;localStorage.setItem('cts-desk-episode',id);if(id&&!Array.from($('#episode').options).some(o=>o.value===id))$('#episode').add(new Option(next?.title||id,id));$('#episode').value=id;$('#episode-summary').textContent=episode?`${episode.title} · ${episode.status}. ${episode.fileList?.length||0} saved files.`:'Choose an episode to see its audio and artwork.';renderAssets();}
$('#episode').onchange=()=>loadEpisode($('#episode').value).catch(e=>notice(e.message,true));
function allMedia(){return [...(episode?.fileList||[]).map(f=>({...f,type:'draft',id:episode.id})),...(project?.files||[]).map(f=>({...f,type:'project',id:project.id}))].filter(f=>/\.(png|jpe?g|webp|mp4|webm|mp3|wav|m4a|ogg)$/i.test(f.name));}
function renderAssets(){const media=allMedia();$('#assets').innerHTML=media.length?media.map(f=>{const url=fileURL(f.type,f.id,f.name);return `<article class="asset">${/\.(png|jpe?g|webp)$/i.test(f.name)?`<img src="${url}" alt="${esc(f.name)}" loading="lazy">`:/\.(mp4|webm)$/i.test(f.name)?`<video src="${url}" controls preload="metadata"></video>`:`<audio src="${url}" controls preload="none"></audio>`}<footer>${esc(f.name)}<a href="${url}" download>Download ${f.type==='draft'?'episode':'folder'} asset</a></footer></article>`;}).join(''):'<p class="empty">Your generated images, audio and trailers will appear here. Choose an episode or research folder to get started.</p>';const previous=$('#audio-source').value;$('#audio-source').innerHTML='<option value="">Or choose saved audio</option>'+media.filter(f=>/\.(mp3|wav|m4a|ogg|webm)$/i.test(f.name)).map(f=>`<option value="${fileURL(f.type,f.id,f.name)}">${esc(f.name)}</option>`).join('');$('#audio-source').value=previous;}
bind('#refresh-assets',async()=>{await Promise.all([loadEpisode(selectedEpisode),refreshProject()]);});
$$('[data-kind]').forEach(b=>b.onclick=()=>{$$('[data-kind]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#image-controls').hidden=b.dataset.kind!=='image';$('#trailer-controls').hidden=b.dataset.kind!=='trailer';});
$$('[data-preset]').forEach(b=>b.onclick=()=>{$('#prompt').value=b.dataset.preset+$('#prompt').value;$('#prompt').focus();});
bind('#generate',async()=>{const prompt=$('#prompt').value.trim();if(!prompt)throw new Error('Describe the image you want to generate.');const target=$('#destination').value;const id=target==='project'?needProject():needEpisode();await api('/api/workspace/generate','POST',{target,id,prompt,aspect:$('#aspect').value});notice('Image generation started. Follow Production activity for the result.');await refreshJobs();});
async function runTrailer(action){const id=needEpisode();if(!episode.fileList?.some(f=>f.name==='episode.mp3'))throw new Error('Make or import the episode voice first, in Podcast episodes.');const seconds=Number($('#clip-length').value),start=Number($('#clip-start').value);if(!Number.isFinite(seconds)||seconds<10||seconds>90||!Number.isFinite(start)||start<0)throw new Error('Choose a length between 10 and 90 seconds and a non-negative start.');await api('/api/run','POST',{action,id,seconds,clip:seconds,start});notice('Video job started. Follow Production activity for the result.');await refreshJobs();}
bind('#trailer',()=>runTrailer('trailer'));bind('#audiogram',()=>runTrailer('social'));
let jobStatus='';
async function refreshJobs(){const jobs=await api('/api/jobs');$('#jobs').innerHTML=jobs.length?jobs.slice(-5).reverse().map(j=>`<div class="activity">${esc(j.action)}<small>${j.done?(j.code===0?'Complete':'Failed — open details'):'Working'}${j.draft?' · '+esc(drafts.get(j.draft)?.title||j.draft):''}</small><button data-job="${esc(j.id)}">Details</button></div>`).join(''):'<p class="hint">No jobs in this server session.</p>';$$('[data-job]').forEach(b=>b.onclick=async()=>{try{const j=await api(`/api/job/${enc(b.dataset.job)}`);$('#job-log').textContent=j.log||'Waiting for output...';$('#job-log').parentElement.open=true;}catch(e){notice(e.message,true);}});const status=JSON.stringify(jobs.map(j=>[j.id,j.done]));if(jobStatus&&status!==jobStatus&&jobs.some(j=>j.done))await Promise.all([loadEpisode(selectedEpisode),refreshProject(),window.ctsRelease?.refresh()]);jobStatus=status;}
async function openAudio(bytes,name){if(bytes.byteLength>200*1024*1024)throw new Error('Use an audio file under 200 MB.');audioContext??=new AudioContext();const buffer=await audioContext.decodeAudioData(bytes);if(buffer.duration>7200)throw new Error('Use an audio file shorter than two hours.');audioBuffer=buffer;peaks=null;$('#audio-help').textContent='Click the waveform to set the start; Shift-click to set the end. Preview edit applies the range, volume and fades to playback.';audioName=name.replace(/\.[^.]+$/,'');$('#audio-name').textContent=name;$('#audio-duration').textContent=`${buffer.duration.toFixed(2)} S · ${buffer.numberOfChannels} CH · ${buffer.sampleRate} HZ`;resetAudio();['#preview-audio','#reset-audio','#download-audio','#save-audio'].forEach(s=>$(s).disabled=false);notice('Audio loaded. Set the range below, then preview your edit.');}
$('#audio-upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>200*1024*1024)throw new Error('Use an audio file under 200 MB.');await openAudio(await file.arrayBuffer(),file.name);}catch(e){notice('Could not open audio: '+e.message,true);}finally{e.target.value='';}};
bind('#load-audio',async()=>{const url=$('#audio-source').value;if(!url)throw new Error('Choose saved audio first.');const r=await fetch(url);if(!r.ok)throw new Error('The audio file could not be read.');await openAudio(await r.arrayBuffer(),$('#audio-source').selectedOptions[0].textContent);});
function settings(){return{start:Number($('#trim-start').value),end:Number($('#trim-end').value),gain:Number($('#gain').value),fadeIn:Number($('#fade-in').value),fadeOut:Number($('#fade-out').value)};}
function rendered(){if(!audioBuffer)throw new Error('Load an audio file first.');const channels=Array.from({length:audioBuffer.numberOfChannels},(_,i)=>audioBuffer.getChannelData(i));return new Blob([wavBytes(editPCM(channels,audioBuffer.sampleRate,settings()),audioBuffer.sampleRate)],{type:'audio/wav'});}
function setPlayer(blob){$('#player').pause();if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(blob);$('#player').src=audioURL;}
function resetAudio(){if(!audioBuffer)return;$('#trim-start').value=0;$('#trim-end').value=audioBuffer.duration;$('#gain').value=0;$('#fade-in').value=0;$('#fade-out').value=0;setPlayer(rendered());drawWave();}
function drawWave(){const canvas=$('#wave'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);if(!audioBuffer){ctx.fillStyle='#b4b4bd';ctx.font='16px Segoe UI';ctx.textAlign='center';ctx.fillText('Your waveform will appear here',w/2,h/2);return;}const data=audioBuffer.getChannelData(0),s=settings();if(!peaks){peaks=Array.from({length:w},(_,x)=>{let min=0,max=0;const from=Math.floor(x*data.length/w),to=Math.min(data.length,Math.max(from+1,Math.floor((x+1)*data.length/w)));for(let i=from;i<to;i++){min=Math.min(min,data[i]);max=Math.max(max,data[i]);}return[min,max];});}ctx.fillStyle='#f4c20d18';ctx.fillRect(s.start/audioBuffer.duration*w,0,(s.end-s.start)/audioBuffer.duration*w,h);ctx.strokeStyle='#e0b945';ctx.beginPath();for(let x=0;x<w;x++){const [min,max]=peaks[x];ctx.moveTo(x,h/2+min*h*.44);ctx.lineTo(x,h/2+max*h*.44);}ctx.stroke();ctx.strokeStyle='#f7f7f8';for(const t of [s.start,s.end]){ctx.beginPath();ctx.moveTo(t/audioBuffer.duration*w,0);ctx.lineTo(t/audioBuffer.duration*w,h);ctx.stroke();}$('#selection-duration').textContent=`Selection: ${Math.max(0,s.end-s.start).toFixed(2)} seconds`;}
$('#wave').onclick=e=>{if(!audioBuffer)return;const rect=e.currentTarget.getBoundingClientRect(),t=Math.max(0,Math.min(audioBuffer.duration,(e.clientX-rect.left)/rect.width*audioBuffer.duration));$(e.shiftKey?'#trim-end':'#trim-start').value=t.toFixed(2);drawWave();};
$$('.edit-controls input').forEach(i=>i.oninput=drawWave);
bind('#preview-audio',async()=>{setPlayer(rendered());await $('#player').play();});bind('#reset-audio',resetAudio);
bind('#download-audio',()=>download(rendered(),uniqueName(audioName+'-edit.wav')));
bind('#save-audio',async()=>{const id=needProject(),blob=rendered(),name=uniqueName(audioName+'-edit.wav');if(blob.size>200*1024*1024)throw new Error('This WAV exceeds 200 MB. Trim a shorter selection or use Download WAV.');await api(`/api/project/${enc(id)}/upload?name=${enc(name)}`,'POST',blob);await refreshProject();notice(`Saved ${name}. Original audio preserved.`);});
mountProduction({api,notice,esc,download,show,refreshJobs,setEpisode:loadEpisode});
mountRelease({api,notice,esc,download,show,setEpisode:loadEpisode,setProject:async id=>{if(dirty)await saveNotes();if(busyChat)throw new Error('Wait for workspace chat to finish.');await listProjects();await loadProject(id);$('#project').value=id;}});
show(location.hash.slice(1)||'overview');
async function init(){await listProjects();const list=await api('/api/drafts');list.forEach(d=>drafts.set(d.id,d));$('#episode').innerHTML='<option value="">Choose an episode</option>'+list.map(d=>`<option value="${esc(d.id)}">${esc(d.title)} · ${esc(d.status)}</option>`).join('');if(drafts.has(selectedEpisode))$('#episode').value=selectedEpisode;else selectedEpisode='';await Promise.all([loadProject($('#project').value),loadEpisode(selectedEpisode),refreshJobs()]);}
init().then(()=>{window.ctsWorkspaceReady=true;window.dispatchEvent(new Event('cts-workspace-ready'));}).catch(e=>notice('Could not load the workspace: '+e.message,true));
setInterval(()=>refreshJobs().catch(()=>{$('#jobs').textContent='Connection lost. Refresh the app to reconnect.';}),5000);
